# Generated by tests/aot/isa/make_cases.py: BASE forms 144..191 of the Jaguar's
# instructions (tools/isa_audit), each as its bytes; undefined flags cleared after it.
.text
.globl _start
_start:
    .byte 0xc1, 0xc9, 0x01  # ror ecx, 0x01
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xc1, 0x4f, 0x40, 0x01  # ror dword ptr [rdi+0x40], 0x01
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xc1, 0xd1, 0x01  # rcl ecx, 0x01
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xc1, 0x57, 0x40, 0x01  # rcl dword ptr [rdi+0x40], 0x01
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xc1, 0xd9, 0x01  # rcr ecx, 0x01
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xc1, 0x5f, 0x40, 0x01  # rcr dword ptr [rdi+0x40], 0x01
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xc1, 0xe1, 0x01  # shl ecx, 0x01
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xc1, 0x67, 0x40, 0x01  # shl dword ptr [rdi+0x40], 0x01
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xc1, 0xe9, 0x01  # shr ecx, 0x01
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xc1, 0x6f, 0x40, 0x01  # shr dword ptr [rdi+0x40], 0x01
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xc1, 0xf9, 0x01  # sar ecx, 0x01
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xc1, 0x7f, 0x40, 0x01  # sar dword ptr [rdi+0x40], 0x01
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xc6, 0x47, 0x40, 0x01  # mov byte ptr [rdi+0x40], 0x01
    .byte 0xc7, 0x47, 0x40, 0x01, 0x02, 0x03, 0x04  # mov dword ptr [rdi+0x40], 0x4030201
    .byte 0xd2, 0xc1  # rol cl, cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd2, 0x47, 0x40  # rol byte ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd2, 0xc9  # ror cl, cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd2, 0x4f, 0x40  # ror byte ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd2, 0xd1  # rcl cl, cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd2, 0x57, 0x40  # rcl byte ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd2, 0xd9  # rcr cl, cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd2, 0x5f, 0x40  # rcr byte ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd2, 0xe1  # shl cl, cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd2, 0x67, 0x40  # shl byte ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd2, 0xe9  # shr cl, cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd2, 0x6f, 0x40  # shr byte ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd2, 0xf9  # sar cl, cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd2, 0x7f, 0x40  # sar byte ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd3, 0xc1  # rol ecx, cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd3, 0x47, 0x40  # rol dword ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd3, 0xc9  # ror ecx, cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd3, 0x4f, 0x40  # ror dword ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd3, 0xd1  # rcl ecx, cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd3, 0x57, 0x40  # rcl dword ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd3, 0xd9  # rcr ecx, cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd3, 0x5f, 0x40  # rcr dword ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ff, (%rsp); popfq
    .byte 0xd3, 0xe1  # shl ecx, cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd3, 0x67, 0x40  # shl dword ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd3, 0xe9  # shr ecx, cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd3, 0x6f, 0x40  # shr dword ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd3, 0xf9  # sar ecx, cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xd3, 0x7f, 0x40  # sar dword ptr [rdi+0x40], cl
    pushfq; andq $0x7ffff7ef, (%rsp); popfq
    .byte 0xf6, 0x47, 0x40, 0x01  # test byte ptr [rdi+0x40], 0x01
    pushfq; andq $0x7fffffef, (%rsp); popfq
    .byte 0xf6, 0xd1  # not cl
    .byte 0xf6, 0x57, 0x40  # not [rdi+0x40]
    .byte 0xf6, 0xd9  # neg cl
    .byte 0xf6, 0x5f, 0x40  # neg [rdi+0x40]
    .byte 0xf6, 0xe1  # mul cl
    pushfq; andq $0x7fffff2b, (%rsp); popfq
    ret
