# Generated by tests/aot/isa/make_cases.py: LZCNT forms 0..3 of the Jaguar's
# instructions (tools/isa_audit), each as its bytes; undefined flags cleared after it.
.text
.globl _start
_start:
    .byte 0xf3, 0x0f, 0xbd, 0xc1  # lzcnt eax, ecx
    pushfq; andq $0x7ffff76b, (%rsp); popfq
    .byte 0xf3, 0x0f, 0xbd, 0x47, 0x40  # lzcnt eax, [rdi+0x40]
    pushfq; andq $0x7ffff76b, (%rsp); popfq
    .byte 0xf3, 0x48, 0x0f, 0xbd, 0xc1  # lzcnt rax, rcx
    pushfq; andq $0x7ffff76b, (%rsp); popfq
    .byte 0xf3, 0x48, 0x0f, 0xbd, 0x47, 0x40  # lzcnt rax, [rdi+0x40]
    pushfq; andq $0x7ffff76b, (%rsp); popfq
    ret
