# Generated by tests/aot/isa/make_cases.py: MOVBE forms 0..2 of the Jaguar's
# instructions (tools/isa_audit), each as its bytes; undefined flags cleared after it.
.text
.globl _start
_start:
    .byte 0x0f, 0x38, 0xf0, 0x47, 0x40  # movbe eax, [rdi+0x40]
    .byte 0x48, 0x0f, 0x38, 0xf0, 0x47, 0x40  # movbe rax, [rdi+0x40]
    .byte 0x66, 0x0f, 0x38, 0xf0, 0x47, 0x40  # movbe ax, [rdi+0x40]
    ret
