# Generated by tests/aot/isa/make_cases.py: SSE forms 96..98 of the Jaguar's
# instructions (tools/isa_audit), each as its bytes; undefined flags cleared after it.
.text
.globl _start
_start:
    .byte 0xf3, 0x48, 0x0f, 0x2c, 0x47, 0x40  # cvttss2si rax, dword ptr [rdi+0x40]
    .byte 0xf3, 0x48, 0x0f, 0x2d, 0xc1  # cvtss2si rax, xmm1
    .byte 0xf3, 0x48, 0x0f, 0x2d, 0x47, 0x40  # cvtss2si rax, dword ptr [rdi+0x40]
    ret
