# Generated by tests/aot/isa/make_cases.py: LONGMODE forms 0..8 of the Jaguar's
# instructions (tools/isa_audit), each as its bytes; undefined flags cleared after it.
.text
.globl _start
_start:
    .byte 0x63, 0xc1  # movsxd eax, ecx
    .byte 0x63, 0x47, 0x40  # movsxd eax, [rdi+0x40]
    .byte 0x48, 0x63, 0xc1  # movsxd rax, ecx
    .byte 0x48, 0x63, 0x47, 0x40  # movsxd rax, dword ptr [rdi+0x40]
    .byte 0x48, 0x98  # cdqe
    .byte 0x48, 0x99  # cqo
    .byte 0x48, 0x0f, 0xc7, 0x4f, 0x40  # cmpxchg16b [rdi+0x40]
    .byte 0x66, 0x63, 0xc1  # movsxd ax, cx
    .byte 0x66, 0x63, 0x47, 0x40  # movsxd ax, dword ptr [rdi+0x40]
    ret
