# Generated by tests/aot/isa/make_cases.py: PCLMULQDQ forms 0..1 of the Jaguar's
# instructions (tools/isa_audit), each as its bytes; undefined flags cleared after it.
.text
.globl _start
_start:
    .byte 0x66, 0x0f, 0x3a, 0x44, 0xc1, 0x01  # pclmulqdq xmm0, xmm1, 0x01
    .byte 0x66, 0x0f, 0x3a, 0x44, 0x47, 0x40, 0x01  # pclmulqdq xmm0, [rdi+0x40], 0x01
    ret
