# Generated by tests/aot/isa/make_cases.py: AMD3DNOW_PREFETCH forms 0..1 of the Jaguar's
# instructions (tools/isa_audit), each as its bytes; undefined flags cleared after it.
.text
.globl _start
_start:
    .byte 0x0f, 0x0d, 0x47, 0x40  # prefetch [rdi+0x40]
    .byte 0x0f, 0x0d, 0x4f, 0x40  # prefetchw [rdi+0x40]
    ret
