# Generated by tests/aot/gen/x87_random.py (seed 1234, 1500 steps): do not edit.
.text
.globl _start
_start:
    mov $0x600000, %rdi
    lea k(%rip), %rsi
    fildl 1324(%rsi)
    fildll 1380(%rsi)
    filds 1308(%rsi)
    fldcw 1406(%rsi)
    fistpll 256(%rdi)
    fnclex
    fnstsw 264(%rdi)
    fdiv %st, %st(1)
    fxam
    xor %eax, %eax
    fcmovnu %st(1), %st
    fucomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 266(%rdi)
    mov %cl, 267(%rdi)
    mov %dl, 268(%rdi)
    fnstsw 269(%rdi)
    fildl 1336(%rsi)
    fildll 1380(%rsi)
    fprem
    fprem
    fnstsw 271(%rdi)
    fld %st(2)
    fsubs 1300(%rsi)
    fucomip %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 273(%rdi)
    mov %cl, 274(%rdi)
    mov %dl, 275(%rdi)
    fxam
    fnstsw 276(%rdi)
    filds 1312(%rsi)
    fld %st(2)
    fnstsw 278(%rdi)
    fstpl 280(%rdi)
    fnstsw 288(%rdi)
    fildll 1380(%rsi)
    fld %st(3)
    fsqrt
    fmul %st, %st(2)
    fcoms 1292(%rsi)
    fld %st(4)
    fmul %st, %st(2)
    fnclex
    fmul %st, %st(5)
    fnstsw 290(%rdi)
    fprem
    fld %st(3)
    fsubrl 1192(%rsi)
    ficoml 1332(%rsi)
    fnstsw 292(%rdi)
    fldcw 1406(%rsi)
    fdivrs 1276(%rsi)
    fldcw 1400(%rsi)
    fmul %st, %st(4)
    fstpt 294(%rdi)
    fcomi %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 304(%rdi)
    mov %cl, 305(%rdi)
    mov %dl, 306(%rdi)
    fnstsw 307(%rdi)
    fsqrt
    fld %st(1)
    fldcw 1392(%rsi)
    fnstsw 309(%rdi)
    fsubr %st, %st(5)
    fxtract
    fld %st(1)
    fxch %st(6)
    fprem1
    fistpl 311(%rdi)
    fnclex
    fld %st(3)
    fxtract
    fcomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 315(%rdi)
    mov %cl, 316(%rdi)
    mov %dl, 317(%rdi)
    fdiv %st(5), %st
    fiaddl 1336(%rsi)
    fnstsw 318(%rdi)
    fcoml 1176(%rsi)
    fdiv %st, %st(3)
    fnstsw 320(%rdi)
    fcomi %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 322(%rdi)
    mov %cl, 323(%rdi)
    mov %dl, 324(%rdi)
    fnstsw 325(%rdi)
    fnclex
    fnstsw 327(%rdi)
    fistpll 329(%rdi)
    fsub %st(2), %st
    fldt 48(%rsi)
    fxtract
    fnstsw 337(%rdi)
    fprem
    fisubrl 1336(%rsi)
    fnstsw 339(%rdi)
    fdivp %st, %st(5)
    fucomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 341(%rdi)
    mov %cl, 342(%rdi)
    mov %dl, 343(%rdi)
    fld %st(4)
    fnstsw 344(%rdi)
    fmul %st, %st(5)
    fidivl 1328(%rsi)
    fsubp %st, %st(5)
    fnstsw 346(%rdi)
    xor %eax, %eax
    fcmovu %st(3), %st
    fnstsw 348(%rdi)
    fld %st(5)
    fld %st(3)
    fstps 350(%rdi)
    fdivrl 1248(%rsi)
    fscale
    fstps 354(%rdi)
    fsubr %st(3), %st
    fimull 1324(%rsi)
    fnstsw 358(%rdi)
    fdivp %st, %st(5)
    fnstsw 360(%rdi)
    fdivl 1240(%rsi)
    fsubrp %st, %st(2)
    fdivl 1208(%rsi)
    fildll 1364(%rsi)
    fdivl 1224(%rsi)
    fsubr %st, %st(1)
    fsubrp %st, %st(1)
    fildl 1320(%rsi)
    fsubs 1272(%rsi)
    fnstsw 362(%rdi)
    fldl 1224(%rsi)
    fmulp %st, %st(2)
    clc
    fcmovnu %st(3), %st
    fnstsw 364(%rdi)
    fildll 1380(%rsi)
    fdivr %st, %st(3)
    fnstsw 366(%rdi)
    fnclex
    fcoms 1276(%rsi)
    fstpt 368(%rdi)
    fprem
    fxch %st(1)
    fadd %st(4), %st
    fildl 1324(%rsi)
    fisubrl 1336(%rsi)
    fnstsw 378(%rdi)
    ftst
    fucom %st(1)
    fisttpll 380(%rdi)
    fimull 1316(%rsi)
    fxch %st(1)
    fldt 912(%rsi)
    fildll 1348(%rsi)
    fld %st(1)
    fld %st(1)
    fxtract
    ftst
    fnstsw 388(%rdi)
    fxtract
    ficoml 1336(%rsi)
    fadds 1288(%rsi)
    fld %st(3)
    fnstsw 390(%rdi)
    fmulp %st, %st(7)
    fcomip %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 392(%rdi)
    mov %cl, 393(%rdi)
    mov %dl, 394(%rdi)
    fnstsw 395(%rdi)
    fnclex
    fldcw 1404(%rsi)
    fnstsw 397(%rdi)
    fldt 192(%rsi)
    fistps 399(%rdi)
    fld %st(5)
    fscale
    fucom %st(5)
    fnstsw 401(%rdi)
    fdivrl 1264(%rsi)
    fadds 1276(%rsi)
    fcoml 1224(%rsi)
    fmul %st, %st(3)
    fnstsw 403(%rdi)
    fstpt 405(%rdi)
    fld %st(5)
    fcomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 415(%rdi)
    mov %cl, 416(%rdi)
    mov %dl, 417(%rdi)
    fdivrs 1296(%rsi)
    fnstsw 418(%rdi)
    fnclex
    fnstsw 420(%rdi)
    fstps 422(%rdi)
    fdivs 1288(%rsi)
    fsubs 1296(%rsi)
    fmulp %st, %st(2)
    fnstsw 426(%rdi)
    fldt 528(%rsi)
    fcomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 428(%rdi)
    mov %cl, 429(%rdi)
    mov %dl, 430(%rdi)
    fsubrp %st, %st(4)
    fnstsw 431(%rdi)
    fld %st(4)
    fmul %st(4), %st
    fnstsw 433(%rdi)
    fstps 435(%rdi)
    fnstsw 439(%rdi)
    filds 1306(%rsi)
    fldl2e
    fld %st(1)
    ficoml 1332(%rsi)
    fld %st(2)
    fld %st(5)
    fnstsw 441(%rdi)
    fld %st(1)
    fnstsw 443(%rdi)
    fnclex
    fldcw 1390(%rsi)
    fnstsw 445(%rdi)
    fnclex
    mov $3, %eax
    cmp $5, %eax
    fcmovne %st(6), %st
    fnclex
    fdivrl 1232(%rsi)
    fld %st(3)
    fld %st(4)
    fstpt 447(%rdi)
    fnstsw 457(%rdi)
    fcoml 1232(%rsi)
    fadds 1284(%rsi)
    faddp %st, %st(6)
    fld %st(3)
    fnstsw 459(%rdi)
    fld %st(3)
    fnstsw 461(%rdi)
    fidivrl 1332(%rsi)
    fld %st(7)
    ftst
    fxam
    fcoml 1256(%rsi)
    fnstsw 463(%rdi)
    fsubp %st, %st(3)
    fnstsw 465(%rdi)
    fistpl 467(%rdi)
    fucomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 471(%rdi)
    mov %cl, 472(%rdi)
    mov %dl, 473(%rdi)
    fnstsw 474(%rdi)
    filds 1308(%rsi)
    fld %st(5)
    fucomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 476(%rdi)
    mov %cl, 477(%rdi)
    mov %dl, 478(%rdi)
    fnstsw 479(%rdi)
    fstpt 481(%rdi)
    fldl 1264(%rsi)
    fdivl 1232(%rsi)
    fadd %st, %st(4)
    fxtract
    fnclex
    fcoml 1264(%rsi)
    fucomip %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 491(%rdi)
    mov %cl, 492(%rdi)
    mov %dl, 493(%rdi)
    fnstsw 494(%rdi)
    fld %st(2)
    fnstsw 496(%rdi)
    fldcw 1408(%rsi)
    fldcw 1388(%rsi)
    fdivrp %st, %st(3)
    fnstsw 498(%rdi)
    mov $7, %eax
    cmp $7, %eax
    fcmovnbe %st(5), %st
    fnstsw 500(%rdi)
    fmuls 1280(%rsi)
    fnstsw 502(%rdi)
    fstpt 504(%rdi)
    fnstsw 514(%rdi)
    fld %st(4)
    fld %st(1)
    fnstsw 516(%rdi)
    fld %st(3)
    fnstsw 518(%rdi)
    fscale
    fld %st(2)
    fnstsw 520(%rdi)
    fidivl 1320(%rsi)
    fnstsw 522(%rdi)
    faddl 1248(%rsi)
    fnclex
    fnstsw 524(%rdi)
    fucomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 526(%rdi)
    mov %cl, 527(%rdi)
    mov %dl, 528(%rdi)
    fld %st(1)
    fcoms 1300(%rsi)
    ficoml 1324(%rsi)
    fldcw 1406(%rsi)
    fnstsw 529(%rdi)
    fscale
    fnstsw 531(%rdi)
    fistpl 533(%rdi)
    fld %st(3)
    fcomi %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 537(%rdi)
    mov %cl, 538(%rdi)
    mov %dl, 539(%rdi)
    fucomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 540(%rdi)
    mov %cl, 541(%rdi)
    mov %dl, 542(%rdi)
    fld %st(7)
    fnstsw 543(%rdi)
    fdivs 1300(%rsi)
    fnstsw 545(%rdi)
    fsubrp %st, %st(5)
    fnstsw 547(%rdi)
    fcomi %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 549(%rdi)
    mov %cl, 550(%rdi)
    mov %dl, 551(%rdi)
    fstpt 552(%rdi)
    fcomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 562(%rdi)
    mov %cl, 563(%rdi)
    mov %dl, 564(%rdi)
    fsqrt
    fucomi %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 565(%rdi)
    mov %cl, 566(%rdi)
    mov %dl, 567(%rdi)
    filds 1310(%rsi)
    fldt 560(%rsi)
    fdivrp %st, %st(5)
    fnclex
    filds 1308(%rsi)
    fld %st(3)
    fsubr %st(7), %st
    fnstsw 568(%rdi)
    fxam
    fsubr %st, %st(3)
    fstps 570(%rdi)
    fnstsw 574(%rdi)
    fsubrp %st, %st(4)
    fldl2t
    fld %st(5)
    fmulp %st, %st(2)
    fnstsw 576(%rdi)
    fsubrl 1248(%rsi)
    fnstsw 578(%rdi)
    mov $3, %eax
    cmp $5, %eax
    fcmovnbe %st(6), %st
    fstpl 580(%rdi)
    fnstsw 588(%rdi)
    mov $3, %eax
    cmp $5, %eax
    fcmovnb %st(3), %st
    flds 1280(%rsi)
    fmuls 1288(%rsi)
    fnstsw 590(%rdi)
    fabs
    fnstsw 592(%rdi)
    faddl 1176(%rsi)
    fld %st(3)
    fnstsw 594(%rdi)
    fcom %st(1)
    fucom %st(7)
    fstpl 596(%rdi)
    fnstsw 604(%rdi)
    fxtract
    fnstsw 606(%rdi)
    fdivs 1288(%rsi)
    fistps 608(%rdi)
    fcomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 610(%rdi)
    mov %cl, 611(%rdi)
    mov %dl, 612(%rdi)
    flds 1284(%rsi)
    fxch %st(5)
    fcoml 1208(%rsi)
    stc
    fcmovnb %st(5), %st
    fxch %st(2)
    fnstsw 613(%rdi)
    fistpll 615(%rdi)
    fdivr %st(4), %st
    fld %st(5)
    fstpt 623(%rdi)
    fnstsw 633(%rdi)
    fsubrs 1288(%rsi)
    frndint
    fxtract
    fsubs 1296(%rsi)
    fnstsw 635(%rdi)
    fld %st(1)
    fscale
    fnstsw 637(%rdi)
    fucomip %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 639(%rdi)
    mov %cl, 640(%rdi)
    mov %dl, 641(%rdi)
    ftst
    fidivrl 1328(%rsi)
    faddl 1240(%rsi)
    fxch %st(4)
    fxch %st(5)
    fxch %st(3)
    fnstsw 642(%rdi)
    fcom %st(3)
    fnstsw 644(%rdi)
    fldcw 1404(%rsi)
    fxam
    fldcw 1394(%rsi)
    fldcw 1400(%rsi)
    fld %st(4)
    fucom %st(7)
    frndint
    fstp %st(7)
    fnstsw 646(%rdi)
    fdivr %st, %st(2)
    mov $3, %eax
    cmp $5, %eax
    fcmovb %st(1), %st
    fld %st(4)
    fld %st(7)
    fnclex
    fld %st(2)
    fnstsw 648(%rdi)
    fld %st(6)
    fxch %st(2)
    fldcw 1390(%rsi)
    fnstsw 650(%rdi)
    fsubr %st(3), %st
    fcomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 652(%rdi)
    mov %cl, 653(%rdi)
    mov %dl, 654(%rdi)
    fnstsw 655(%rdi)
    fsqrt
    fsubrs 1280(%rsi)
    fdivr %st(1), %st
    fld %st(3)
    fld %st(6)
    fnstsw 657(%rdi)
    fisubl 1324(%rsi)
    fnstsw 659(%rdi)
    fadd %st, %st(7)
    fnstsw 661(%rdi)
    fmuls 1300(%rsi)
    fldcw 1396(%rsi)
    fdiv %st, %st(7)
    fsubrp %st, %st(1)
    fnstsw 663(%rdi)
    fucomi %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 665(%rdi)
    mov %cl, 666(%rdi)
    mov %dl, 667(%rdi)
    fnstsw 668(%rdi)
    fxtract
    fld %st(1)
    fdivrs 1280(%rsi)
    fnstsw 670(%rdi)
    fabs
    fnclex
    fsubs 1280(%rsi)
    fdivp %st, %st(4)
    fstpl 672(%rdi)
    fldl 1208(%rsi)
    fistpll 680(%rdi)
    fstps 688(%rdi)
    fildl 1332(%rsi)
    fildll 1340(%rsi)
    fld %st(6)
    fld %st(4)
    fmul %st(6), %st
    fnclex
    fstp %st(6)
    fnstsw 692(%rdi)
    fucomi %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 694(%rdi)
    mov %cl, 695(%rdi)
    mov %dl, 696(%rdi)
    fldcw 1402(%rsi)
    fldcw 1392(%rsi)
    fnstsw 697(%rdi)
    frndint
    fxch %st(5)
    fxch %st(4)
    fnstsw 699(%rdi)
    fsqrt
    fnclex
    fdivrl 1240(%rsi)
    fcomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 701(%rdi)
    mov %cl, 702(%rdi)
    mov %dl, 703(%rdi)
    fnstsw 704(%rdi)
    fldcw 1392(%rsi)
    fstpt 706(%rdi)
    fchs
    fnstsw 716(%rdi)
    clc
    fcmove %st(5), %st
    fnstsw 718(%rdi)
    fchs
    fnstsw 720(%rdi)
    fld %st(2)
    fnstsw 722(%rdi)
    fxch %st(3)
    fcomi %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 724(%rdi)
    mov %cl, 725(%rdi)
    mov %dl, 726(%rdi)
    fistpll 727(%rdi)
    fxch %st(1)
    fld %st(2)
    fucom %st(5)
    fld %st(4)
    fxtract
    xor %eax, %eax
    fcmovbe %st(1), %st
    fnstsw 735(%rdi)
    fnclex
    fnstsw 737(%rdi)
    ficoml 1316(%rsi)
    fnstsw 739(%rdi)
    fld %st(1)
    fld %st(7)
    fnstsw 741(%rdi)
    fldcw 1402(%rsi)
    fxtract
    fnstsw 743(%rdi)
    fstl 745(%rdi)
    ficoml 1336(%rsi)
    fimull 1332(%rsi)
    ficoml 1332(%rsi)
    fisttpll 753(%rdi)
    fdivr %st(4), %st
    fnstsw 761(%rdi)
    fcomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 763(%rdi)
    mov %cl, 764(%rdi)
    mov %dl, 765(%rdi)
    fxch %st(3)
    fldl 1224(%rsi)
    fxtract
    fnstsw 766(%rdi)
    fld %st(6)
    fld %st(5)
    fld %st(1)
    fimull 1328(%rsi)
    fld %st(3)
    fnstsw 768(%rdi)
    fistpl 770(%rdi)
    fstpt 774(%rdi)
    fdivs 1300(%rsi)
    fprem1
    fnstsw 784(%rdi)
    fldl 1208(%rsi)
    fld %st(3)
    fld %st(7)
    fmul %st, %st(1)
    fnstsw 786(%rdi)
    fxtract
    fnstsw 788(%rdi)
    fsubr %st, %st(3)
    fnstsw 790(%rdi)
    fld %st(7)
    fnstsw 792(%rdi)
    fmul %st, %st(1)
    fld %st(6)
    fnstsw 794(%rdi)
    fxch %st(4)
    fdivrs 1288(%rsi)
    fld %st(3)
    fnstsw 796(%rdi)
    fimull 1336(%rsi)
    fmul %st(3), %st
    fnstsw 798(%rdi)
    fdivrs 1280(%rsi)
    fld %st(1)
    fld %st(6)
    fld %st(3)
    fld %st(5)
    fucomi %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 800(%rdi)
    mov %cl, 801(%rdi)
    mov %dl, 802(%rdi)
    fld %st(1)
    fld %st(7)
    fnstsw 803(%rdi)
    fcomip %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 805(%rdi)
    mov %cl, 806(%rdi)
    mov %dl, 807(%rdi)
    fnstsw 808(%rdi)
    fdivs 1276(%rsi)
    fnstsw 810(%rdi)
    fcomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 812(%rdi)
    mov %cl, 813(%rdi)
    mov %dl, 814(%rdi)
    fld %st(6)
    fprem1
    fxam
    fxch %st(5)
    fnstsw 815(%rdi)
    fldcw 1402(%rsi)
    fsubrp %st, %st(7)
    fnstsw 817(%rdi)
    fistps 819(%rdi)
    fdivrl 1264(%rsi)
    filds 1314(%rsi)
    fxch %st(3)
    fxtract
    fnstsw 821(%rdi)
    fld %st(6)
    fdivl 1264(%rsi)
    fstp %st(4)
    fsqrt
    fld %st(6)
    fnstsw 823(%rdi)
    fsubp %st, %st(2)
    fxch %st(6)
    fnstsw 825(%rdi)
    fld %st(6)
    fnstsw 827(%rdi)
    mov $5, %eax
    cmp $3, %eax
    fcmovne %st(2), %st
    fxtract
    fnstsw 829(%rdi)
    mov $5, %eax
    cmp $3, %eax
    fcmovnu %st(3), %st
    fdivr %st, %st(3)
    fnstsw 831(%rdi)
    fcomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 833(%rdi)
    mov %cl, 834(%rdi)
    mov %dl, 835(%rdi)
    fsubp %st, %st(1)
    fstl 836(%rdi)
    fsubp %st, %st(5)
    fistps 844(%rdi)
    fnstsw 846(%rdi)
    fprem
    fprem1
    fnstsw 848(%rdi)
    fildl 1328(%rsi)
    filds 1314(%rsi)
    fnclex
    fnstsw 850(%rdi)
    fcomip %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 852(%rdi)
    mov %cl, 853(%rdi)
    mov %dl, 854(%rdi)
    fdivl 1256(%rsi)
    clc
    fcmovbe %st(5), %st
    fnclex
    fsubs 1292(%rsi)
    fnstsw 855(%rdi)
    flds 1292(%rsi)
    fld %st(6)
    fucomi %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 857(%rdi)
    mov %cl, 858(%rdi)
    mov %dl, 859(%rdi)
    fld %st(7)
    fnclex
    fnstsw 860(%rdi)
    fld %st(6)
    fxtract
    fnstsw 862(%rdi)
    fsub %st, %st(6)
    mov $3, %eax
    cmp $5, %eax
    fcmovbe %st(5), %st
    fld %st(6)
    fdivrp %st, %st(1)
    fmuls 1272(%rsi)
    mov $7, %eax
    cmp $7, %eax
    fcmovu %st(6), %st
    fnstsw 864(%rdi)
    fnclex
    fcomip %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 866(%rdi)
    mov %cl, 867(%rdi)
    mov %dl, 868(%rdi)
    fnstsw 869(%rdi)
    fxtract
    fsubl 1200(%rsi)
    fxam
    fnstsw 871(%rdi)
    fxtract
    fistps 873(%rdi)
    fnstsw 875(%rdi)
    fsub %st(5), %st
    fldcw 1388(%rsi)
    fxch %st(2)
    fnstsw 877(%rdi)
    fxch %st(2)
    fld %st(5)
    fnstsw 879(%rdi)
    fcomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 881(%rdi)
    mov %cl, 882(%rdi)
    mov %dl, 883(%rdi)
    fstpl 884(%rdi)
    fidivrl 1336(%rsi)
    fistpll 892(%rdi)
    flds 1276(%rsi)
    fistpll 900(%rdi)
    fadd %st(1), %st
    fadds 1284(%rsi)
    fucomip %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 908(%rdi)
    mov %cl, 909(%rdi)
    mov %dl, 910(%rdi)
    fnclex
    fdivs 1280(%rsi)
    fstpt 911(%rdi)
    fcomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 921(%rdi)
    mov %cl, 922(%rdi)
    mov %dl, 923(%rdi)
    fldl 1232(%rsi)
    fstp %st(2)
    fnstsw 924(%rdi)
    fmul %st(2), %st
    mov $5, %eax
    cmp $3, %eax
    fcmovu %st(1), %st
    flds 1300(%rsi)
    fld %st(1)
    fnclex
    fnstsw 926(%rdi)
    fldlg2
    fld %st(4)
    fscale
    fnstsw 928(%rdi)
    fdiv %st(5), %st
    fnstsw 930(%rdi)
    fimull 1316(%rsi)
    fnstsw 932(%rdi)
    fcom %st(3)
    fistpl 934(%rdi)
    fnstsw 938(%rdi)
    fldl 1200(%rsi)
    fcoms 1284(%rsi)
    fld %st(4)
    fnstsw 940(%rdi)
    fxam
    fnstsw 942(%rdi)
    fucomi %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 944(%rdi)
    mov %cl, 945(%rdi)
    mov %dl, 946(%rdi)
    fld %st(3)
    fxch %st(3)
    fld %st(4)
    fnstsw 947(%rdi)
    mov $5, %eax
    cmp $3, %eax
    fcmovnu %st(4), %st
    fnstsw 949(%rdi)
    fdivr %st(5), %st
    fcoms 1300(%rsi)
    fld %st(7)
    fsubr %st(5), %st
    fnstsw 951(%rdi)
    fld %st(3)
    fnstsw 953(%rdi)
    fidivrl 1320(%rsi)
    fucomi %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 955(%rdi)
    mov %cl, 956(%rdi)
    mov %dl, 957(%rdi)
    fnclex
    fnstsw 958(%rdi)
    fld %st(1)
    fnstsw 960(%rdi)
    fxtract
    fld %st(5)
    fabs
    fnstsw 962(%rdi)
    fistps 964(%rdi)
    fsubs 1288(%rsi)
    fld %st(2)
    fnstsw 966(%rdi)
    fmull 1192(%rsi)
    fchs
    fstp %st(4)
    faddp %st, %st(4)
    fsubrs 1272(%rsi)
    fcom %st(3)
    fnstsw 968(%rdi)
    flds 1296(%rsi)
    fstpt 970(%rdi)
    fadds 1272(%rsi)
    fxtract
    mov $3, %eax
    cmp $5, %eax
    fcmove %st(5), %st
    fsubr %st(4), %st
    fdivr %st(3), %st
    fnstsw 980(%rdi)
    fld %st(4)
    fnstsw 982(%rdi)
    fmull 1264(%rsi)
    fnstsw 984(%rdi)
    fstpt 986(%rdi)
    fld %st(4)
    fxch %st(5)
    fnstsw 996(%rdi)
    fdivr %st, %st(4)
    fsubrp %st, %st(2)
    fnstsw 998(%rdi)
    fld %st(3)
    fnstsw 1000(%rdi)
    fld %st(2)
    fdivr %st, %st(1)
    fmull 1256(%rsi)
    fnstsw 1002(%rdi)
    fnclex
    fnstsw 1004(%rdi)
    fxch %st(5)
    fucom %st(1)
    fnstsw 1006(%rdi)
    fld %st(5)
    fld %st(2)
    fnstsw 1008(%rdi)
    fld %st(4)
    fld %st(3)
    frndint
    fldcw 1392(%rsi)
    fsubr %st, %st(3)
    fadd %st, %st(6)
    fnclex
    fnstsw 1010(%rdi)
    fld %st(7)
    fld %st(5)
    fnclex
    fnstsw 1012(%rdi)
    fnclex
    fnstsw 1014(%rdi)
    fsubr %st(1), %st
    fld %st(7)
    fcomip %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1016(%rdi)
    mov %cl, 1017(%rdi)
    mov %dl, 1018(%rdi)
    fldcw 1406(%rsi)
    fnstsw 1019(%rdi)
    fmull 1168(%rsi)
    fxtract
    fnstsw 1021(%rdi)
    fistpll 1023(%rdi)
    fnstsw 1031(%rdi)
    fxtract
    fnclex
    fld %st(3)
    fchs
    fnstsw 1033(%rdi)
    fxtract
    fnstsw 1035(%rdi)
    xor %eax, %eax
    fcmovbe %st(3), %st
    fnstsw 1037(%rdi)
    fstp %st(6)
    fdivr %st, %st(6)
    fcoml 1216(%rsi)
    fisubrl 1320(%rsi)
    fcom %st(5)
    fistps 1039(%rdi)
    fnstsw 1041(%rdi)
    flds 1292(%rsi)
    fxch %st(6)
    fnstsw 1043(%rdi)
    fxam
    fchs
    fld %st(5)
    fnstsw 1045(%rdi)
    fdivr %st(1), %st
    fcoml 1208(%rsi)
    fdivrl 1232(%rsi)
    fnstsw 1047(%rdi)
    fdiv %st, %st(2)
    fnclex
    fnstsw 1049(%rdi)
    fucomi %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1051(%rdi)
    mov %cl, 1052(%rdi)
    mov %dl, 1053(%rdi)
    mov $7, %eax
    cmp $7, %eax
    fcmovnb %st(7), %st
    fnstsw 1054(%rdi)
    frndint
    fsubl 1192(%rsi)
    fnstsw 1056(%rdi)
    fstpt 1058(%rdi)
    fnstsw 1068(%rdi)
    xor %eax, %eax
    fcmovu %st(1), %st
    fxch %st(2)
    fnstsw 1070(%rdi)
    faddl 1248(%rsi)
    mov $7, %eax
    cmp $7, %eax
    fcmovb %st(1), %st
    fxch %st(5)
    fld %st(1)
    fnstsw 1072(%rdi)
    fxch %st(2)
    fnstsw 1074(%rdi)
    fxch %st(2)
    fnstsw 1076(%rdi)
    fdivrl 1168(%rsi)
    fnstsw 1078(%rdi)
    fmull 1240(%rsi)
    fnstsw 1080(%rdi)
    fstp %st(4)
    fstp %st(6)
    fnstsw 1082(%rdi)
    fadd %st, %st(1)
    fld %st(4)
    fnstsw 1084(%rdi)
    fxch %st(2)
    fmull 1200(%rsi)
    fnstsw 1086(%rdi)
    fdivrs 1292(%rsi)
    fnclex
    faddl 1200(%rsi)
    fnstsw 1088(%rdi)
    fld %st(6)
    fld %st(1)
    fnstsw 1090(%rdi)
    fcoms 1296(%rsi)
    fcomi %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1092(%rdi)
    mov %cl, 1093(%rdi)
    mov %dl, 1094(%rdi)
    fmulp %st, %st(4)
    fnclex
    fnstsw 1095(%rdi)
    fstps 1097(%rdi)
    mov $7, %eax
    cmp $7, %eax
    fcmovnu %st(5), %st
    fsub %st(3), %st
    fnclex
    fiaddl 1332(%rsi)
    fnstsw 1101(%rdi)
    fnclex
    fnstsw 1103(%rdi)
    fldt 688(%rsi)
    fstpt 1105(%rdi)
    fildll 1356(%rsi)
    fxtract
    fidivl 1320(%rsi)
    fnstsw 1115(%rdi)
    fistps 1117(%rdi)
    fxtract
    fucomi %st(7), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1119(%rdi)
    mov %cl, 1120(%rdi)
    mov %dl, 1121(%rdi)
    fnstsw 1122(%rdi)
    fld %st(1)
    fnstsw 1124(%rdi)
    fstl 1126(%rdi)
    fnstsw 1134(%rdi)
    fdivr %st(4), %st
    fdivr %st, %st(5)
    fnstsw 1136(%rdi)
    fld %st(3)
    fnstsw 1138(%rdi)
    fld %st(5)
    fmul %st(1), %st
    fnstsw 1140(%rdi)
    fnclex
    fnstsw 1142(%rdi)
    fstl 1144(%rdi)
    fnstsw 1152(%rdi)
    fld %st(4)
    fld %st(2)
    fnstsw 1154(%rdi)
    fistps 1156(%rdi)
    fnstsw 1158(%rdi)
    fdivl 1232(%rsi)
    fnstsw 1160(%rdi)
    fsub %st, %st(6)
    fisubl 1316(%rsi)
    fstl 1162(%rdi)
    fnstsw 1170(%rdi)
    fldcw 1396(%rsi)
    mov $7, %eax
    cmp $7, %eax
    fcmove %st(6), %st
    fld %st(1)
    fxch %st(1)
    fcomip %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1172(%rdi)
    mov %cl, 1173(%rdi)
    mov %dl, 1174(%rdi)
    fxch %st(5)
    fnstsw 1175(%rdi)
    fxch %st(6)
    fxtract
    fistpll 1177(%rdi)
    fiaddl 1316(%rsi)
    fmuls 1288(%rsi)
    fld %st(3)
    fnclex
    fld %st(3)
    fnstsw 1185(%rdi)
    mov $7, %eax
    cmp $7, %eax
    fcmovb %st(5), %st
    fxch %st(1)
    fnstsw 1187(%rdi)
    fldcw 1390(%rsi)
    fnstsw 1189(%rdi)
    fsubrl 1232(%rsi)
    fnstsw 1191(%rdi)
    fsubrs 1276(%rsi)
    fnstsw 1193(%rdi)
    fmuls 1284(%rsi)
    fnstsw 1195(%rdi)
    fsubl 1176(%rsi)
    fnstsw 1197(%rdi)
    fucomi %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1199(%rdi)
    mov %cl, 1200(%rdi)
    mov %dl, 1201(%rdi)
    fnstsw 1202(%rdi)
    mov $7, %eax
    cmp $7, %eax
    fcmovnb %st(7), %st
    fnstsw 1204(%rdi)
    mov $7, %eax
    cmp $7, %eax
    fcmove %st(1), %st
    fxtract
    fucomi %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1206(%rdi)
    mov %cl, 1207(%rdi)
    mov %dl, 1208(%rdi)
    fstpl 1209(%rdi)
    fnstsw 1217(%rdi)
    fidivrl 1328(%rsi)
    fnclex
    fld %st(6)
    fld %st(2)
    fidivl 1332(%rsi)
    fprem1
    fnstsw 1219(%rdi)
    fldcw 1410(%rsi)
    fnstsw 1221(%rdi)
    clc
    fcmovnbe %st(6), %st
    fprem1
    fnclex
    fld %st(5)
    fsubrp %st, %st(1)
    fnstsw 1223(%rdi)
    fxch %st(6)
    fld %st(5)
    fstpl 1225(%rdi)
    ficoml 1316(%rsi)
    fnstsw 1233(%rdi)
    fdivp %st, %st(2)
    fnstsw 1235(%rdi)
    fadds 1292(%rsi)
    fld %st(2)
    fcomi %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1237(%rdi)
    mov %cl, 1238(%rdi)
    mov %dl, 1239(%rdi)
    fnstsw 1240(%rdi)
    fsubrs 1280(%rsi)
    fxch %st(4)
    fnstsw 1242(%rdi)
    fcom %st(4)
    fistps 1244(%rdi)
    fldcw 1390(%rsi)
    fmuls 1272(%rsi)
    filds 1304(%rsi)
    clc
    fcmovb %st(4), %st
    fnstsw 1246(%rdi)
    fabs
    fnstsw 1248(%rdi)
    fdiv %st(3), %st
    mov $7, %eax
    cmp $7, %eax
    fcmovne %st(1), %st
    fidivrl 1336(%rsi)
    fdivr %st(4), %st
    fimull 1328(%rsi)
    fldcw 1390(%rsi)
    fisubl 1336(%rsi)
    fstpl 1250(%rdi)
    fnstsw 1258(%rdi)
    fildll 1380(%rsi)
    fsubrs 1296(%rsi)
    fld %st(1)
    fnstsw 1260(%rdi)
    fld %st(1)
    fucom %st(7)
    fucom %st(7)
    fiaddl 1320(%rsi)
    fnstsw 1262(%rdi)
    fxtract
    fprem1
    fcoml 1232(%rsi)
    fdiv %st(5), %st
    fldcw 1404(%rsi)
    fcoms 1292(%rsi)
    fnstsw 1264(%rdi)
    fld %st(1)
    fld %st(5)
    fnstsw 1266(%rdi)
    fsubl 1256(%rsi)
    fstl 1268(%rdi)
    fnstsw 1276(%rdi)
    fdiv %st, %st(4)
    fldcw 1396(%rsi)
    fchs
    fidivl 1336(%rsi)
    ficoml 1324(%rsi)
    fnstsw 1278(%rdi)
    frndint
    fnstsw 1280(%rdi)
    fdivrs 1288(%rsi)
    faddp %st, %st(4)
    fnstsw 1282(%rdi)
    fadd %st, %st(3)
    fmul %st(3), %st
    fucom %st(6)
    fnstsw 1284(%rdi)
    fcomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1286(%rdi)
    mov %cl, 1287(%rdi)
    mov %dl, 1288(%rdi)
    fnclex
    fxtract
    fsubp %st, %st(4)
    fcom %st(5)
    fxtract
    fcomip %st(7), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1289(%rdi)
    mov %cl, 1290(%rdi)
    mov %dl, 1291(%rdi)
    fld %st(4)
    fnstsw 1292(%rdi)
    mov $7, %eax
    cmp $7, %eax
    fcmove %st(5), %st
    fnstsw 1294(%rdi)
    ficoml 1328(%rsi)
    fcoms 1276(%rsi)
    fnstsw 1296(%rdi)
    fxch %st(7)
    fxch %st(4)
    fidivl 1316(%rsi)
    fmuls 1296(%rsi)
    fnstsw 1298(%rdi)
    frndint
    fldcw 1390(%rsi)
    fxtract
    fnstsw 1300(%rdi)
    fstp %st(6)
    fidivl 1324(%rsi)
    fxch %st(1)
    fsub %st(5), %st
    fnstsw 1302(%rdi)
    fldcw 1410(%rsi)
    fnstsw 1304(%rdi)
    fld %st(2)
    fnstsw 1306(%rdi)
    fstps 1308(%rdi)
    fstl 1312(%rdi)
    ftst
    fnstsw 1320(%rdi)
    fucom %st(3)
    fstps 1322(%rdi)
    fisttpll 1326(%rdi)
    fxch %st(2)
    fnstsw 1334(%rdi)
    fxtract
    fnstsw 1336(%rdi)
    fdivrs 1300(%rsi)
    flds 1300(%rsi)
    fld %st(6)
    fnstsw 1338(%rdi)
    fnclex
    fistps 1340(%rdi)
    fld %st(5)
    fnstsw 1342(%rdi)
    fcomi %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1344(%rdi)
    mov %cl, 1345(%rdi)
    mov %dl, 1346(%rdi)
    fstl 1347(%rdi)
    fdivrl 1176(%rsi)
    fnstsw 1355(%rdi)
    fcoms 1280(%rsi)
    fstpt 1357(%rdi)
    fnstsw 1367(%rdi)
    fcom %st(1)
    fadd %st, %st(3)
    fstps 1369(%rdi)
    fld %st(1)
    fnstsw 1373(%rdi)
    fxtract
    fnstsw 1375(%rdi)
    fadds 1292(%rsi)
    fnstsw 1377(%rdi)
    fxch %st(2)
    fxtract
    fxam
    fxam
    fnstsw 1379(%rdi)
    fld %st(4)
    fidivl 1316(%rsi)
    fxtract
    fld %st(5)
    fcom %st(4)
    fnstsw 1381(%rdi)
    fld %st(4)
    fmull 1168(%rsi)
    fnstsw 1383(%rdi)
    fld %st(7)
    fcomi %st(7), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1385(%rdi)
    mov %cl, 1386(%rdi)
    mov %dl, 1387(%rdi)
    fisttpll 1388(%rdi)
    fld %st(3)
    fdivs 1276(%rsi)
    fnstsw 1396(%rdi)
    fistpll 1398(%rdi)
    fnstsw 1406(%rdi)
    fsubs 1300(%rsi)
    fsub %st(2), %st
    fnstsw 1408(%rdi)
    fcoms 1292(%rsi)
    fnstsw 1410(%rdi)
    fnclex
    fsqrt
    fnstsw 1412(%rdi)
    fld %st(1)
    fnstsw 1414(%rdi)
    fmulp %st, %st(3)
    fsub %st(6), %st
    fnclex
    fistpl 1416(%rdi)
    fnstsw 1420(%rdi)
    fistps 1422(%rdi)
    fld %st(1)
    fldt 976(%rsi)
    fistps 1424(%rdi)
    fnstsw 1426(%rdi)
    fldcw 1396(%rsi)
    fxtract
    fcomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1428(%rdi)
    mov %cl, 1429(%rdi)
    mov %dl, 1430(%rdi)
    flds 1288(%rsi)
    fadd %st(6), %st
    fdivp %st, %st(2)
    fstps 1431(%rdi)
    filds 1304(%rsi)
    faddl 1256(%rsi)
    fcoms 1288(%rsi)
    fprem
    fldcw 1400(%rsi)
    fdivrs 1296(%rsi)
    fxch %st(4)
    fnstsw 1435(%rdi)
    fsubp %st, %st(5)
    fnstsw 1437(%rdi)
    fildl 1316(%rsi)
    fldlg2
    fnclex
    fnstsw 1439(%rdi)
    fucomip %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1441(%rdi)
    mov %cl, 1442(%rdi)
    mov %dl, 1443(%rdi)
    faddl 1224(%rsi)
    fistpl 1444(%rdi)
    fcom %st(3)
    fldcw 1410(%rsi)
    fnstsw 1448(%rdi)
    frndint
    fildll 1372(%rsi)
    fldcw 1392(%rsi)
    fnstsw 1450(%rdi)
    fld1
    fistps 1452(%rdi)
    fnstsw 1454(%rdi)
    fld %st(2)
    fsub %st(1), %st
    fsubrp %st, %st(6)
    flds 1296(%rsi)
    fldcw 1396(%rsi)
    fstp %st(3)
    fildl 1336(%rsi)
    fsubl 1248(%rsi)
    fldcw 1396(%rsi)
    fucomip %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1456(%rdi)
    mov %cl, 1457(%rdi)
    mov %dl, 1458(%rdi)
    fnstsw 1459(%rdi)
    fldl 1240(%rsi)
    fldcw 1398(%rsi)
    fnclex
    fnstsw 1461(%rdi)
    fsubrp %st, %st(2)
    fnstsw 1463(%rdi)
    fstpl 1465(%rdi)
    fldz
    fidivl 1320(%rsi)
    fildl 1332(%rsi)
    fxtract
    faddl 1224(%rsi)
    fdivs 1300(%rsi)
    fld %st(4)
    fnstsw 1473(%rdi)
    fistps 1475(%rdi)
    fucomi %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1477(%rdi)
    mov %cl, 1478(%rdi)
    mov %dl, 1479(%rdi)
    fld %st(2)
    fnstsw 1480(%rdi)
    fnclex
    fld %st(4)
    fsubrl 1256(%rsi)
    fucomip %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1482(%rdi)
    mov %cl, 1483(%rdi)
    mov %dl, 1484(%rdi)
    fnstsw 1485(%rdi)
    fld %st(5)
    fnclex
    fnstsw 1487(%rdi)
    fdivp %st, %st(3)
    fnstsw 1489(%rdi)
    fld %st(3)
    fnstsw 1491(%rdi)
    fcom %st(2)
    fsubr %st, %st(1)
    fnstsw 1493(%rdi)
    fld %st(5)
    fld %st(5)
    fld %st(1)
    fld %st(7)
    fsubp %st, %st(3)
    fldcw 1400(%rsi)
    fucomip %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1495(%rdi)
    mov %cl, 1496(%rdi)
    mov %dl, 1497(%rdi)
    fsubr %st, %st(5)
    fadds 1292(%rsi)
    fnclex
    fldt 96(%rsi)
    fld %st(6)
    fnstsw 1498(%rdi)
    fstp %st(3)
    fdivs 1292(%rsi)
    fld %st(3)
    fstps 1500(%rdi)
    fsubl 1224(%rsi)
    fld %st(5)
    fnstsw 1504(%rdi)
    fsubp %st, %st(3)
    fistps 1506(%rdi)
    fcomi %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1508(%rdi)
    mov %cl, 1509(%rdi)
    mov %dl, 1510(%rdi)
    fnstsw 1511(%rdi)
    fnclex
    fsubrl 1240(%rsi)
    mov $3, %eax
    cmp $5, %eax
    fcmove %st(5), %st
    fnstsw 1513(%rdi)
    fxtract
    fiaddl 1336(%rsi)
    fld %st(1)
    fmuls 1300(%rsi)
    fcoml 1208(%rsi)
    fxch %st(3)
    fnstsw 1515(%rdi)
    fucom %st(1)
    fnstsw 1517(%rdi)
    fld %st(1)
    fcoml 1240(%rsi)
    fsubr %st(1), %st
    fld %st(1)
    fnstsw 1519(%rdi)
    fidivl 1324(%rsi)
    fnstsw 1521(%rdi)
    fld %st(1)
    fistpll 1523(%rdi)
    fnstsw 1531(%rdi)
    fabs
    fldcw 1402(%rsi)
    fld %st(6)
    fnstsw 1533(%rdi)
    fmul %st, %st(4)
    clc
    fcmove %st(6), %st
    fdivr %st, %st(1)
    fnstsw 1535(%rdi)
    fucomip %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1537(%rdi)
    mov %cl, 1538(%rdi)
    mov %dl, 1539(%rdi)
    fldcw 1400(%rsi)
    fcomip %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1540(%rdi)
    mov %cl, 1541(%rdi)
    mov %dl, 1542(%rdi)
    fnstsw 1543(%rdi)
    fdivp %st, %st(4)
    fildll 1364(%rsi)
    fildll 1372(%rsi)
    fsub %st, %st(1)
    fnstsw 1545(%rdi)
    fnclex
    fmuls 1280(%rsi)
    fdivp %st, %st(4)
    fnstsw 1547(%rdi)
    fsubrp %st, %st(3)
    fldt 288(%rsi)
    fadd %st(4), %st
    fildl 1316(%rsi)
    fld %st(4)
    fldcw 1400(%rsi)
    fnstsw 1549(%rdi)
    fmull 1256(%rsi)
    fmul %st(1), %st
    fnstsw 1551(%rdi)
    fxch %st(7)
    fstp %st(4)
    fabs
    fld %st(1)
    fldcw 1390(%rsi)
    fnstsw 1553(%rdi)
    fld %st(3)
    fstl 1555(%rdi)
    fnstsw 1563(%rdi)
    fldcw 1408(%rsi)
    fnstsw 1565(%rdi)
    stc
    fcmove %st(7), %st
    fsub %st(6), %st
    fnstsw 1567(%rdi)
    fldcw 1394(%rsi)
    fld %st(7)
    fld %st(4)
    fld %st(7)
    fnstsw 1569(%rdi)
    fsubrs 1280(%rsi)
    fnstsw 1571(%rdi)
    ficoml 1336(%rsi)
    fstl 1573(%rdi)
    fnstsw 1581(%rdi)
    fld %st(3)
    fld %st(5)
    fld %st(4)
    fabs
    fnstsw 1583(%rdi)
    fxch %st(2)
    fnclex
    fxtract
    fsubs 1300(%rsi)
    fmulp %st, %st(4)
    fld %st(5)
    fnstsw 1585(%rdi)
    fnclex
    fld %st(4)
    fucomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1587(%rdi)
    mov %cl, 1588(%rdi)
    mov %dl, 1589(%rdi)
    fnstsw 1590(%rdi)
    fld %st(4)
    fdivrs 1288(%rsi)
    fldcw 1394(%rsi)
    fucomi %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1592(%rdi)
    mov %cl, 1593(%rdi)
    mov %dl, 1594(%rdi)
    fld %st(4)
    fnstsw 1595(%rdi)
    fstpl 1597(%rdi)
    fnclex
    fnstsw 1605(%rdi)
    fld %st(4)
    fdivrs 1288(%rsi)
    fnstsw 1607(%rdi)
    fstl 1609(%rdi)
    fcomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1617(%rdi)
    mov %cl, 1618(%rdi)
    mov %dl, 1619(%rdi)
    fnstsw 1620(%rdi)
    ficoml 1328(%rsi)
    fnclex
    fstps 1622(%rdi)
    fnstsw 1626(%rdi)
    fscale
    fisubrl 1316(%rsi)
    fld %st(1)
    fstpt 1628(%rdi)
    fld %st(2)
    fxch %st(6)
    fadds 1296(%rsi)
    fnstsw 1638(%rdi)
    fisubl 1316(%rsi)
    fld %st(4)
    fsubs 1292(%rsi)
    fnstsw 1640(%rdi)
    fucomi %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1642(%rdi)
    mov %cl, 1643(%rdi)
    mov %dl, 1644(%rdi)
    fld %st(2)
    fstps 1645(%rdi)
    fstps 1649(%rdi)
    fdivp %st, %st(1)
    fnstsw 1653(%rdi)
    fsubs 1296(%rsi)
    fnstsw 1655(%rdi)
    fucomi %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1657(%rdi)
    mov %cl, 1658(%rdi)
    mov %dl, 1659(%rdi)
    fnstsw 1660(%rdi)
    fdivrs 1300(%rsi)
    fnstsw 1662(%rdi)
    fxtract
    fucom %st(4)
    fstl 1664(%rdi)
    fxch %st(4)
    fld %st(5)
    fstpt 1672(%rdi)
    fmull 1232(%rsi)
    fisubl 1316(%rsi)
    fld %st(3)
    fnstsw 1682(%rdi)
    fld %st(4)
    fcomip %st(7), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1684(%rdi)
    mov %cl, 1685(%rdi)
    mov %dl, 1686(%rdi)
    fld %st(2)
    fcomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1687(%rdi)
    mov %cl, 1688(%rdi)
    mov %dl, 1689(%rdi)
    fld %st(6)
    fmul %st(1), %st
    fnstsw 1690(%rdi)
    fdivrs 1272(%rsi)
    fldcw 1388(%rsi)
    fldcw 1406(%rsi)
    fnstsw 1692(%rdi)
    stc
    fcmovnb %st(5), %st
    fnstsw 1694(%rdi)
    fsubr %st(5), %st
    fmuls 1288(%rsi)
    fnstsw 1696(%rdi)
    fprem
    faddp %st, %st(1)
    fnstsw 1698(%rdi)
    fadd %st, %st(2)
    fprem1
    fadd %st, %st(3)
    fnstsw 1700(%rdi)
    fsub %st, %st(3)
    fnclex
    fldcw 1396(%rsi)
    fnstsw 1702(%rdi)
    ficoml 1336(%rsi)
    fcoml 1192(%rsi)
    fdivr %st, %st(4)
    fld %st(1)
    fdivr %st, %st(2)
    fld %st(4)
    fsubp %st, %st(7)
    fdivs 1272(%rsi)
    fcomi %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1704(%rdi)
    mov %cl, 1705(%rdi)
    mov %dl, 1706(%rdi)
    fxtract
    fsubs 1276(%rsi)
    stc
    fcmovnbe %st(7), %st
    fcomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1707(%rdi)
    mov %cl, 1708(%rdi)
    mov %dl, 1709(%rdi)
    fcoms 1292(%rsi)
    fnstsw 1710(%rdi)
    fsub %st(4), %st
    fstp %st(1)
    fnstsw 1712(%rdi)
    fistpl 1714(%rdi)
    fnstsw 1718(%rdi)
    fildl 1328(%rsi)
    fcoms 1292(%rsi)
    fsubr %st(4), %st
    fnstsw 1720(%rdi)
    fistpll 1722(%rdi)
    fscale
    fxch %st(2)
    fnstsw 1730(%rdi)
    fldl 1216(%rsi)
    fcomip %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1732(%rdi)
    mov %cl, 1733(%rdi)
    mov %dl, 1734(%rdi)
    fildl 1336(%rsi)
    fldcw 1402(%rsi)
    fxch %st(5)
    fnstsw 1735(%rdi)
    fld %st(5)
    fstpt 1737(%rdi)
    fnstsw 1747(%rdi)
    fildl 1336(%rsi)
    xor %eax, %eax
    fcmovbe %st(2), %st
    fnstsw 1749(%rdi)
    fucom %st(3)
    ficoml 1324(%rsi)
    fdivp %st, %st(6)
    fnstsw 1751(%rdi)
    fld %st(5)
    fnstsw 1753(%rdi)
    fxch %st(4)
    fnstsw 1755(%rdi)
    fsubp %st, %st(6)
    fld %st(4)
    fsubrl 1168(%rsi)
    fnstsw 1757(%rdi)
    fiaddl 1336(%rsi)
    fnstsw 1759(%rdi)
    fsubrl 1216(%rsi)
    fxtract
    fdivrs 1300(%rsi)
    fnstsw 1761(%rdi)
    fld %st(3)
    fnstsw 1763(%rdi)
    fld %st(1)
    fld %st(3)
    fld %st(2)
    fsub %st(7), %st
    fld %st(2)
    fnstsw 1765(%rdi)
    fld %st(4)
    fmuls 1276(%rsi)
    fisubl 1320(%rsi)
    fld %st(7)
    fnstsw 1767(%rdi)
    fstps 1769(%rdi)
    fcomi %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1773(%rdi)
    mov %cl, 1774(%rdi)
    mov %dl, 1775(%rdi)
    fisttpll 1776(%rdi)
    fscale
    fnstsw 1784(%rdi)
    fld %st(2)
    fistps 1786(%rdi)
    fld %st(5)
    fnstsw 1788(%rdi)
    fucomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1790(%rdi)
    mov %cl, 1791(%rdi)
    mov %dl, 1792(%rdi)
    fnstsw 1793(%rdi)
    fcom %st(5)
    fnstsw 1795(%rdi)
    fucom %st(4)
    fnstsw 1797(%rdi)
    fcom %st(4)
    fmul %st(5), %st
    fistpll 1799(%rdi)
    fnstsw 1807(%rdi)
    flds 1296(%rsi)
    mov $5, %eax
    cmp $3, %eax
    fcmovbe %st(3), %st
    fnstsw 1809(%rdi)
    fld %st(5)
    fnstsw 1811(%rdi)
    fucomip %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1813(%rdi)
    mov %cl, 1814(%rdi)
    mov %dl, 1815(%rdi)
    ficoml 1336(%rsi)
    clc
    fcmovnbe %st(5), %st
    ftst
    fstp %st(2)
    fnstsw 1816(%rdi)
    mov $5, %eax
    cmp $3, %eax
    fcmove %st(3), %st
    fildl 1320(%rsi)
    fsqrt
    fnstsw 1818(%rdi)
    fnclex
    fnstsw 1820(%rdi)
    fld %st(1)
    fxch %st(4)
    fnstsw 1822(%rdi)
    fdivr %st, %st(2)
    fnstsw 1824(%rdi)
    ftst
    fnstsw 1826(%rdi)
    fnclex
    fld %st(2)
    ftst
    fldcw 1402(%rsi)
    fldcw 1408(%rsi)
    fld %st(5)
    fsubs 1300(%rsi)
    fnstsw 1828(%rdi)
    fucomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1830(%rdi)
    mov %cl, 1831(%rdi)
    mov %dl, 1832(%rdi)
    fisttpll 1833(%rdi)
    fnstsw 1841(%rdi)
    fdiv %st, %st(1)
    fprem1
    fucom %st(3)
    fnstsw 1843(%rdi)
    fadd %st(2), %st
    fldt 1120(%rsi)
    mov $3, %eax
    cmp $5, %eax
    fcmovu %st(4), %st
    fld %st(4)
    fistpl 1845(%rdi)
    fistpll 1849(%rdi)
    fnstsw 1857(%rdi)
    fildl 1332(%rsi)
    fsubr %st, %st(3)
    fistpl 1859(%rdi)
    fildl 1316(%rsi)
    fcoml 1200(%rsi)
    fnstsw 1863(%rdi)
    fcomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1865(%rdi)
    mov %cl, 1866(%rdi)
    mov %dl, 1867(%rdi)
    fnstsw 1868(%rdi)
    fchs
    fldt 288(%rsi)
    fmulp %st, %st(4)
    fldcw 1392(%rsi)
    fnstsw 1870(%rdi)
    fprem
    fsub %st(3), %st
    ficoml 1328(%rsi)
    fmul %st(2), %st
    fxch %st(5)
    fldcw 1406(%rsi)
    fnclex
    fldl 1176(%rsi)
    fisttpll 1872(%rdi)
    fnstsw 1880(%rdi)
    fld %st(2)
    fnstsw 1882(%rdi)
    frndint
    fld %st(3)
    fdivr %st, %st(1)
    fxtract
    fnstsw 1884(%rdi)
    faddl 1200(%rsi)
    fistps 1886(%rdi)
    fdivp %st, %st(2)
    fnstsw 1888(%rdi)
    fld %st(1)
    fdivr %st, %st(3)
    fnstsw 1890(%rdi)
    fld %st(2)
    fucomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 1892(%rdi)
    mov %cl, 1893(%rdi)
    mov %dl, 1894(%rdi)
    fnstsw 1895(%rdi)
    ficoml 1316(%rsi)
    fsub %st(5), %st
    fnstsw 1897(%rdi)
    fistpl 1899(%rdi)
    fnstsw 1903(%rdi)
    fisttpll 1905(%rdi)
    fldt 832(%rsi)
    fld %st(3)
    fld %st(3)
    fnstsw 1913(%rdi)
    fadds 1272(%rsi)
    fdivrs 1280(%rsi)
    fmuls 1300(%rsi)
    fscale
    fnstsw 1915(%rdi)
    fcom %st(3)
    fnclex
    fnstsw 1917(%rdi)
    fldcw 1390(%rsi)
    fprem
    fabs
    fnstsw 1919(%rdi)
    fprem
    fstp %st(7)
    fnstsw 1921(%rdi)
    frndint
    fnstsw 1923(%rdi)
    fdivrs 1272(%rsi)
    fmul %st(4), %st
    fadd %st, %st(5)
    mov $5, %eax
    cmp $3, %eax
    fcmovnbe %st(5), %st
    fnstsw 1925(%rdi)
    fsubrs 1276(%rsi)
    fxtract
    fstl 1927(%rdi)
    fadd %st(5), %st
    fnstsw 1935(%rdi)
    fisttpll 1937(%rdi)
    fmull 1176(%rsi)
    fdivrl 1256(%rsi)
    fnstsw 1945(%rdi)
    fimull 1324(%rsi)
    fsubr %st(5), %st
    fld %st(6)
    fnstsw 1947(%rdi)
    fstl 1949(%rdi)
    fnstsw 1957(%rdi)
    fnclex
    fisubrl 1324(%rsi)
    fnstsw 1959(%rdi)
    fisubl 1332(%rsi)
    fld %st(7)
    fsub %st(3), %st
    fstpl 1961(%rdi)
    fsqrt
    fisubrl 1328(%rsi)
    fistps 1969(%rdi)
    fnstsw 1971(%rdi)
    fchs
    fistpll 1973(%rdi)
    fdivp %st, %st(1)
    fisttpll 1981(%rdi)
    fld %st(1)
    fnstsw 1989(%rdi)
    filds 1312(%rsi)
    fildl 1320(%rsi)
    fmull 1248(%rsi)
    fldt 192(%rsi)
    fidivrl 1324(%rsi)
    fdivr %st(4), %st
    fnstsw 1991(%rdi)
    clc
    fcmove %st(6), %st
    fmul %st(2), %st
    fxch %st(3)
    fnstsw 1993(%rdi)
    fistps 1995(%rdi)
    fnstsw 1997(%rdi)
    mov $3, %eax
    cmp $5, %eax
    fcmovnu %st(5), %st
    fildl 1324(%rsi)
    fcoml 1184(%rsi)
    fnstsw 1999(%rdi)
    fld %st(5)
    fnstsw 2001(%rdi)
    fcomip %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2003(%rdi)
    mov %cl, 2004(%rdi)
    mov %dl, 2005(%rdi)
    fld %st(3)
    fld %st(1)
    fld %st(4)
    fnclex
    fld %st(4)
    fnstsw 2006(%rdi)
    fld %st(6)
    fnstsw 2008(%rdi)
    fld %st(4)
    fnstsw 2010(%rdi)
    fprem
    fnstsw 2012(%rdi)
    fxch %st(6)
    fnstsw 2014(%rdi)
    fld %st(2)
    fxam
    fstl 2016(%rdi)
    fld %st(4)
    fnstsw 2024(%rdi)
    faddp %st, %st(2)
    fld %st(6)
    fnstsw 2026(%rdi)
    fld %st(6)
    fnstsw 2028(%rdi)
    fadd %st, %st(1)
    fucomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2030(%rdi)
    mov %cl, 2031(%rdi)
    mov %dl, 2032(%rdi)
    fmul %st, %st(2)
    fnstsw 2033(%rdi)
    fisubrl 1324(%rsi)
    fnstsw 2035(%rdi)
    fdivr %st(3), %st
    fnstsw 2037(%rdi)
    fdivrs 1284(%rsi)
    fld %st(1)
    fstps 2039(%rdi)
    fnstsw 2043(%rdi)
    fld %st(3)
    fld %st(7)
    fnstsw 2045(%rdi)
    fxch %st(5)
    fimull 1316(%rsi)
    fnstsw 2047(%rdi)
    fsqrt
    fsubr %st(5), %st
    fldcw 1404(%rsi)
    fxch %st(2)
    fucomi %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2049(%rdi)
    mov %cl, 2050(%rdi)
    mov %dl, 2051(%rdi)
    fxtract
    fnstsw 2052(%rdi)
    fdivrl 1200(%rsi)
    fldcw 1408(%rsi)
    fldcw 1396(%rsi)
    fnstsw 2054(%rdi)
    fld %st(6)
    fstps 2056(%rdi)
    fdiv %st, %st(1)
    fld %st(6)
    fnstsw 2060(%rdi)
    fdiv %st, %st(4)
    fnstsw 2062(%rdi)
    fisttpll 2064(%rdi)
    fnstsw 2072(%rdi)
    fucomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2074(%rdi)
    mov %cl, 2075(%rdi)
    mov %dl, 2076(%rdi)
    flds 1296(%rsi)
    fmul %st(5), %st
    fnstsw 2077(%rdi)
    fdivr %st, %st(5)
    fnstsw 2079(%rdi)
    fld %st(2)
    fnstsw 2081(%rdi)
    fld %st(1)
    fcomip %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2083(%rdi)
    mov %cl, 2084(%rdi)
    mov %dl, 2085(%rdi)
    fistps 2086(%rdi)
    fsubrs 1276(%rsi)
    fldl 1176(%rsi)
    fld %st(4)
    fnstsw 2088(%rdi)
    fcoms 1276(%rsi)
    fnstsw 2090(%rdi)
    fabs
    fstpt 2092(%rdi)
    fldcw 1398(%rsi)
    fnstsw 2102(%rdi)
    fstps 2104(%rdi)
    fsubrp %st, %st(2)
    fscale
    fnstsw 2108(%rdi)
    fldcw 1390(%rsi)
    flds 1276(%rsi)
    fcomi %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2110(%rdi)
    mov %cl, 2111(%rdi)
    mov %dl, 2112(%rdi)
    fidivrl 1328(%rsi)
    fnclex
    fstpl 2113(%rdi)
    fnstsw 2121(%rdi)
    fildll 1364(%rsi)
    fld %st(2)
    fnstsw 2123(%rdi)
    fld %st(4)
    fucom %st(6)
    fcom %st(2)
    fld %st(2)
    fnstsw 2125(%rdi)
    mov $7, %eax
    cmp $7, %eax
    fcmovb %st(1), %st
    fld %st(5)
    fcom %st(1)
    fld %st(1)
    fnstsw 2127(%rdi)
    fxtract
    fstpl 2129(%rdi)
    fimull 1316(%rsi)
    fld %st(2)
    fnstsw 2137(%rdi)
    fsubs 1288(%rsi)
    fnstsw 2139(%rdi)
    fxch %st(4)
    fldcw 1394(%rsi)
    fucomip %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2141(%rdi)
    mov %cl, 2142(%rdi)
    mov %dl, 2143(%rdi)
    fcomip %st(6), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2144(%rdi)
    mov %cl, 2145(%rdi)
    mov %dl, 2146(%rdi)
    fsubrp %st, %st(1)
    fnstsw 2147(%rdi)
    filds 1310(%rsi)
    fnclex
    fscale
    fistpll 2149(%rdi)
    flds 1276(%rsi)
    mov $7, %eax
    cmp $7, %eax
    fcmove %st(1), %st
    fld %st(5)
    fcom %st(6)
    fxam
    fnstsw 2157(%rdi)
    fld %st(1)
    fdivs 1292(%rsi)
    fstl 2159(%rdi)
    ftst
    fnstsw 2167(%rdi)
    fsubl 1224(%rsi)
    fdiv %st, %st(6)
    fsub %st, %st(1)
    fnstsw 2169(%rdi)
    fld %st(2)
    fdivp %st, %st(7)
    fsub %st, %st(6)
    fchs
    ficoml 1316(%rsi)
    fidivl 1336(%rsi)
    fnstsw 2171(%rdi)
    fprem
    fnstsw 2173(%rdi)
    fld %st(3)
    fnstsw 2175(%rdi)
    fdiv %st(2), %st
    fstl 2177(%rdi)
    fmulp %st, %st(4)
    fnstsw 2185(%rdi)
    fxch %st(6)
    fistpl 2187(%rdi)
    fnstsw 2191(%rdi)
    fnclex
    fnstsw 2193(%rdi)
    fldl 1168(%rsi)
    fldcw 1392(%rsi)
    fsubrs 1280(%rsi)
    fnstsw 2195(%rdi)
    ficoml 1336(%rsi)
    fucomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2197(%rdi)
    mov %cl, 2198(%rdi)
    mov %dl, 2199(%rdi)
    fcom %st(3)
    fsubp %st, %st(1)
    fnstsw 2200(%rdi)
    mov $5, %eax
    cmp $3, %eax
    fcmovne %st(3), %st
    fnstsw 2202(%rdi)
    ftst
    fnstsw 2204(%rdi)
    flds 1280(%rsi)
    fnclex
    fstl 2206(%rdi)
    fisttpll 2214(%rdi)
    flds 1272(%rsi)
    fld %st(5)
    fnstsw 2222(%rdi)
    fstl 2224(%rdi)
    fsqrt
    fmull 1232(%rsi)
    mov $7, %eax
    cmp $7, %eax
    fcmove %st(1), %st
    fnstsw 2232(%rdi)
    fstl 2234(%rdi)
    fnclex
    fnstsw 2242(%rdi)
    mov $5, %eax
    cmp $3, %eax
    fcmovne %st(4), %st
    fisttpll 2244(%rdi)
    fnstsw 2252(%rdi)
    fdivrl 1184(%rsi)
    fdivl 1184(%rsi)
    fnstsw 2254(%rdi)
    fld %st(1)
    fdivrs 1272(%rsi)
    ficoml 1328(%rsi)
    fnstsw 2256(%rdi)
    fld %st(3)
    fucom %st(2)
    fcomi %st(7), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2258(%rdi)
    mov %cl, 2259(%rdi)
    mov %dl, 2260(%rdi)
    fistps 2261(%rdi)
    fidivrl 1324(%rsi)
    fcoml 1200(%rsi)
    ficoml 1316(%rsi)
    fucomip %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2263(%rdi)
    mov %cl, 2264(%rdi)
    mov %dl, 2265(%rdi)
    fnstsw 2266(%rdi)
    fcoml 1168(%rsi)
    fldcw 1404(%rsi)
    fnstsw 2268(%rdi)
    fcomi %st(3), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2270(%rdi)
    mov %cl, 2271(%rdi)
    mov %dl, 2272(%rdi)
    fnstsw 2273(%rdi)
    fdivr %st, %st(1)
    fstpl 2275(%rdi)
    fmul %st(1), %st
    filds 1306(%rsi)
    fisubrl 1320(%rsi)
    fld %st(3)
    fstl 2283(%rdi)
    fdivrp %st, %st(3)
    fabs
    fldcw 1400(%rsi)
    fxch %st(5)
    fnstsw 2291(%rdi)
    fnclex
    fnstsw 2293(%rdi)
    fldcw 1390(%rsi)
    fstpl 2295(%rdi)
    fnstsw 2303(%rdi)
    fxtract
    fistpll 2305(%rdi)
    ftst
    fnstsw 2313(%rdi)
    fnclex
    fnstsw 2315(%rdi)
    fsubrs 1276(%rsi)
    fabs
    fchs
    fabs
    fisubl 1336(%rsi)
    fnstsw 2317(%rdi)
    fildl 1320(%rsi)
    fiaddl 1332(%rsi)
    fnstsw 2319(%rdi)
    ftst
    fnstsw 2321(%rdi)
    fldl 1192(%rsi)
    fstl 2323(%rdi)
    fsubr %st(5), %st
    fsubl 1208(%rsi)
    fld %st(5)
    fnstsw 2331(%rdi)
    fnclex
    fstl 2333(%rdi)
    fsubr %st(2), %st
    fldcw 1400(%rsi)
    fadd %st(2), %st
    fldcw 1390(%rsi)
    fnstsw 2341(%rdi)
    fld %st(5)
    fnstsw 2343(%rdi)
    ficoml 1316(%rsi)
    fldcw 1392(%rsi)
    fnstsw 2345(%rdi)
    fld %st(1)
    fldcw 1396(%rsi)
    fisubl 1316(%rsi)
    fnstsw 2347(%rdi)
    fsubrp %st, %st(6)
    fsubrl 1232(%rsi)
    fnstsw 2349(%rdi)
    fldcw 1394(%rsi)
    fld %st(1)
    fisubrl 1332(%rsi)
    fcom %st(6)
    fnstsw 2351(%rdi)
    fabs
    fsub %st(1), %st
    fnstsw 2353(%rdi)
    fimull 1324(%rsi)
    fldcw 1406(%rsi)
    fistps 2355(%rdi)
    fdivrs 1296(%rsi)
    fld %st(1)
    fnstsw 2357(%rdi)
    fsubrp %st, %st(5)
    fstp %st(1)
    fldt 320(%rsi)
    fistpl 2359(%rdi)
    fnstsw 2363(%rdi)
    fsubs 1276(%rsi)
    fdivl 1184(%rsi)
    fld %st(4)
    fnstsw 2365(%rdi)
    fld %st(3)
    fcomip %st(1), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2367(%rdi)
    mov %cl, 2368(%rdi)
    mov %dl, 2369(%rdi)
    faddp %st, %st(5)
    fnstsw 2370(%rdi)
    fildll 1364(%rsi)
    fld %st(5)
    fnstsw 2372(%rdi)
    fucomi %st(5), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2374(%rdi)
    mov %cl, 2375(%rdi)
    mov %dl, 2376(%rdi)
    fnstsw 2377(%rdi)
    fsubrp %st, %st(5)
    fnstsw 2379(%rdi)
    fcomip %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2381(%rdi)
    mov %cl, 2382(%rdi)
    mov %dl, 2383(%rdi)
    fmull 1168(%rsi)
    filds 1310(%rsi)
    fld %st(6)
    fld %st(2)
    fld %st(1)
    fnstsw 2384(%rdi)
    fsubp %st, %st(4)
    mov $7, %eax
    cmp $7, %eax
    fcmovne %st(1), %st
    fisubl 1316(%rsi)
    fsubrp %st, %st(2)
    fnstsw 2386(%rdi)
    fildll 1372(%rsi)
    fscale
    fnstsw 2388(%rdi)
    fldcw 1410(%rsi)
    fnstsw 2390(%rdi)
    fdivr %st(4), %st
    fcomi %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2392(%rdi)
    mov %cl, 2393(%rdi)
    mov %dl, 2394(%rdi)
    fnstsw 2395(%rdi)
    fld %st(1)
    fldcw 1394(%rsi)
    fnstsw 2397(%rdi)
    fisttpll 2399(%rdi)
    fnstsw 2407(%rdi)
    fstpt 2409(%rdi)
    fsub %st(1), %st
    fmuls 1276(%rsi)
    filds 1306(%rsi)
    fistpll 2419(%rdi)
    fnstsw 2427(%rdi)
    fadd %st(4), %st
    fnstsw 2429(%rdi)
    fxam
    fnstsw 2431(%rdi)
    fcomi %st(2), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2433(%rdi)
    mov %cl, 2434(%rdi)
    mov %dl, 2435(%rdi)
    fld %st(4)
    fld %st(3)
    fnstsw 2436(%rdi)
    fdiv %st(2), %st
    ftst
    fldcw 1400(%rsi)
    fucom %st(4)
    fnstsw 2438(%rdi)
    fmuls 1280(%rsi)
    fnstsw 2440(%rdi)
    fsqrt
    fdivr %st(4), %st
    fnstsw 2442(%rdi)
    fdivp %st, %st(3)
    fnstsw 2444(%rdi)
    fld %st(3)
    fprem1
    fstpt 2446(%rdi)
    fsqrt
    fnstsw 2456(%rdi)
    fidivrl 1324(%rsi)
    fxch %st(2)
    fnstsw 2458(%rdi)
    fucom %st(1)
    fstpl 2460(%rdi)
    flds 1276(%rsi)
    fsubs 1276(%rsi)
    ftst
    faddl 1200(%rsi)
    fnstsw 2468(%rdi)
    fld %st(1)
    fdivp %st, %st(3)
    fucomi %st(4), %st
    setb %al
    setz %cl
    setp %dl
    mov %al, 2470(%rdi)
    mov %cl, 2471(%rdi)
    mov %dl, 2472(%rdi)
    fld %st(4)
    fnstsw 2473(%rdi)
    ret
.section .rodata
.balign 16
k:
    .quad 0x8000000000000000
    .short 0x3fff, 0, 0, 0
    .quad 0x8000000000000000
    .short 0xbfff, 0, 0, 0
    .quad 0x0000000000000000
    .short 0x0000, 0, 0, 0
    .quad 0x0000000000000000
    .short 0x8000, 0, 0, 0
    .quad 0x8000000000000000
    .short 0x7fff, 0, 0, 0
    .quad 0x8000000000000000
    .short 0xffff, 0, 0, 0
    .quad 0xc000000000000000
    .short 0x7fff, 0, 0, 0
    .quad 0xc000000000001234
    .short 0xffff, 0, 0, 0
    .quad 0x8000000000000001
    .short 0x7fff, 0, 0, 0
    .quad 0x0000000000000123
    .short 0x0000, 0, 0, 0
    .quad 0x7fffffffffffffff
    .short 0x8000, 0, 0, 0
    .quad 0xffffffffffffffff
    .short 0x7ffe, 0, 0, 0
    .quad 0x8000000000000000
    .short 0x0001, 0, 0, 0
    .quad 0xd8b716aeabeb9592
    .short 0x400c, 0, 0, 0
    .quad 0x83f1b6b004762a22
    .short 0x3f64, 0, 0, 0
    .quad 0xbb558a3a9da618fd
    .short 0xd2fd, 0, 0, 0
    .quad 0x81df0733d868c2cf
    .short 0x1770, 0, 0, 0
    .quad 0xccfcc11e118dc10e
    .short 0x8844, 0, 0, 0
    .quad 0xa6b5fec7a506bfc5
    .short 0x2282, 0, 0, 0
    .quad 0xf032f1f574113cb0
    .short 0x400e, 0, 0, 0
    .quad 0xbc8597beb5c36ec1
    .short 0x3f48, 0, 0, 0
    .quad 0x89a4243029fc1d9d
    .short 0xc008, 0, 0, 0
    .quad 0xc3cca8fff4f991a8
    .short 0x3f93, 0, 0, 0
    .quad 0xd4c9137a46db4bc4
    .short 0xbff9, 0, 0, 0
    .quad 0xec7dd1aaf4687101
    .short 0xbff2, 0, 0, 0
    .quad 0xacbf70c5c3a671c4
    .short 0x8542, 0, 0, 0
    .quad 0xe435bfbf0b9ab366
    .short 0xc05d, 0, 0, 0
    .quad 0xa3348b2f4bb19d02
    .short 0xb845, 0, 0, 0
    .quad 0xc3d0755ff0689ae1
    .short 0x3fbe, 0, 0, 0
    .quad 0x988039a1a41b657a
    .short 0xb03c, 0, 0, 0
    .quad 0xf4390958949606b3
    .short 0x59f1, 0, 0, 0
    .quad 0xe4bc152ccb26e7a5
    .short 0xec89, 0, 0, 0
    .quad 0xf280046c0c386144
    .short 0x3f48, 0, 0, 0
    .quad 0xf766d4a3caf4a2a1
    .short 0x1c16, 0, 0, 0
    .quad 0xa0f36e0495c13a79
    .short 0x4038, 0, 0, 0
    .quad 0x98e8b8bb658aa25d
    .short 0x3ff4, 0, 0, 0
    .quad 0xf1e0dde783d9479c
    .short 0x3ff1, 0, 0, 0
    .quad 0x87b843ab4d4142f8
    .short 0x79ed, 0, 0, 0
    .quad 0x91c1de3355712a55
    .short 0xbff3, 0, 0, 0
    .quad 0xc5e57249d7a384ea
    .short 0x3ff8, 0, 0, 0
    .quad 0x8b3725f3a3665363
    .short 0x3ff4, 0, 0, 0
    .quad 0xa9864ccfbc9a0005
    .short 0xbfde, 0, 0, 0
    .quad 0xa8d377dd6c0a9bba
    .short 0xc086, 0, 0, 0
    .quad 0xb33564456906ab68
    .short 0xbf5f, 0, 0, 0
    .quad 0xa612b55f36c138a4
    .short 0xbf74, 0, 0, 0
    .quad 0xbec8bfbdc6e211a0
    .short 0x3f35, 0, 0, 0
    .quad 0xb28f0e527aeed6af
    .short 0x3ffa, 0, 0, 0
    .quad 0xb343f9082f821d3c
    .short 0xebc3, 0, 0, 0
    .quad 0xccdcfaaba7bcee9f
    .short 0xa401, 0, 0, 0
    .quad 0xd58b32ebcdc4a666
    .short 0x95a2, 0, 0, 0
    .quad 0xe6516d28a9241885
    .short 0xe693, 0, 0, 0
    .quad 0x91ec1931ea84727e
    .short 0x3f1b, 0, 0, 0
    .quad 0xd7d0b32bae78c1bd
    .short 0xc065, 0, 0, 0
    .quad 0xc45b3709128e58f7
    .short 0xc005, 0, 0, 0
    .quad 0xa23d908075417bc5
    .short 0xc05b, 0, 0, 0
    .quad 0x918bf2195f331ded
    .short 0xbff5, 0, 0, 0
    .quad 0x9ab6ff2ef94beb7a
    .short 0x04c9, 0, 0, 0
    .quad 0xc1f4d56ae8a30eca
    .short 0xc040, 0, 0, 0
    .quad 0xca375a8ce8d52b3f
    .short 0xa177, 0, 0, 0
    .quad 0xcae2e6c8aec8cc04
    .short 0x3ffe, 0, 0, 0
    .quad 0xf8537ec8af589885
    .short 0xbfeb, 0, 0, 0
    .quad 0x950625bfb04bf9c4
    .short 0x12a1, 0, 0, 0
    .quad 0xaf93fce70a7788c2
    .short 0x9081, 0, 0, 0
    .quad 0x85b65053e2e548dc
    .short 0xe1a7, 0, 0, 0
    .quad 0xf84aa6cd589faaa2
    .short 0x1d2d, 0, 0, 0
    .quad 0xe72aa2cb72b515ca
    .short 0x4008, 0, 0, 0
    .quad 0xd6a53a4a7c747612
    .short 0x402c, 0, 0, 0
    .quad 0xaf8a69fd97683f68
    .short 0xeea0, 0, 0, 0
    .quad 0xe33e174d36575fb3
    .short 0x098f, 0, 0, 0
    .quad 0xdf21ddeca6b81586
    .short 0xbffc, 0, 0, 0
    .quad 0xb2c590c149d50a0b
    .short 0xae48, 0, 0, 0
    .quad 0xa8082bcde6350092
    .short 0x4078, 0, 0, 0
    .quad 0x9bf9c376dd75afc5
    .short 0x45aa, 0, 0, 0
    .quad 0x3fb999999999999a
    .quad 0xc004000000000000
    .quad 0x7e37e43c8800759c
    .quad 0x81a56e1fc2f8f359
    .quad 0x4008000000000000
    .quad 0x401c000000000000
    .quad 0x3fe0000000000000
    .quad 0x4415af1d78b58c40
    .quad 0x40fe240c9fbe76c9
    .quad 0x8000000000000000
    .quad 0x7ff0000000000000
    .quad 0x7ff8000000000000
    .quad 0x0000000000000001
    .long 0x3fc00000
    .long 0xbdcccccd
    .long 0x7f7fc99e
    .long 0x000116c2
    .long 0x40000000
    .long 0xc0e80000
    .long 0x7f800000
    .long 0x2edbe6ff
    .short 0
    .short 1
    .short -1
    .short 32767
    .short -32768
    .short 1234
    .long 0
    .long 7
    .long -7
    .long 2147483647
    .long -2147483648
    .long 100000007
    .quad 0
    .quad 3
    .quad -3
    .quad 9223372036854775807
    .quad -9223372036854775808
    .quad 81985529216486895
    .short 0x037f
    .short 0x007f
    .short 0x027f
    .short 0x077f
    .short 0x0b7f
    .short 0x0f7f
    .short 0x0e7f
    .short 0x047f
    .short 0x087f
    .short 0x0c7f
    .short 0x0a7f
    .short 0x067f
