#!/bin/sh
# Writes tools/sdk/libVPRuntime.tbd: the symbols a game pack may bind to in the app's runtime
# (runtime/vp_host.c built as Frameworks/libVPRuntime.dylib), as a text stub ld64.lld links against
# on any OS. Input: the runtime built as a shared library (ELF .so or Mach-O .dylib).
#   gen_runtime_tbd.sh RUNTIME_LIB [OUT]          (NM=llvm-nm or nm)
set -e
LIB=$1; OUT=${2:-$(dirname "$0")/libVPRuntime.tbd}; NM=${NM:-nm}
[ -n "$LIB" ] || { echo "usage: $0 RUNTIME_LIB [OUT]" >&2; exit 2; }
SYMS=$($NM -g --defined-only "$LIB" 2>/dev/null | awk '{print $NF}' | sed 's/^_//' | grep '^vp_' | grep -v '^vp_sf_' | sort -u)
{
    echo "--- !tapi-tbd"
    echo "# Generated by tools/sdk/gen_runtime_tbd.sh from runtime/vp_host.c. Do not edit."
    echo "tbd-version:     4"
    echo "targets:         [ arm64-xros, arm64-macos, arm64-ios ]"
    echo "install-name:    '@rpath/libVPRuntime.dylib'"
    echo "current-version: 1"
    echo "exports:"
    echo "  - targets:         [ arm64-xros, arm64-macos, arm64-ios ]"
    echo "    symbols:         [ $(printf '%s\n' $SYMS | sed 's/^/_/' | paste -sd, - | sed 's/,/, /g') ]"
    echo "..."
} > "$OUT"
echo "$(printf '%s\n' $SYMS | wc -l) runtime symbols in $OUT"
