#include <stdio.h>
#include <string.h>
__attribute__((noinline)) int f0(const char* x) { static const char* t = "aliqua magna amet tempor monster et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 0; }
__attribute__((noinline)) int f1(const char* x) { static const char* t = "dolor monster lorem level et sed magna elit adipiscing robot et magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 1; }
__attribute__((noinline)) int f2(const char* x) { static const char* t = "et incididunt mission options amet elit mission amet options dolore incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 2; }
__attribute__((noinline)) int f3(const char* x) { static const char* t = "rescue moon dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 3; }
__attribute__((noinline)) int f4(const char* x) { static const char* t = "moon aliqua ipsum do moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 4; }
__attribute__((noinline)) int f5(const char* x) { static const char* t = "level options sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 5; }
__attribute__((noinline)) int f6(const char* x) { static const char* t = "monster planet incididunt robot loading ut incididunt planet loading aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 6; }
__attribute__((noinline)) int f7(const char* x) { static const char* t = "amet tempor sit ipsum amet et adipiscing sed rescue ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 7; }
__attribute__((noinline)) int f8(const char* x) { static const char* t = "ut dolore level incididunt aliqua tempor magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 8; }
__attribute__((noinline)) int f9(const char* x) { static const char* t = "ut aliqua elit eiusmod rescue lorem options sed monster rescue robot consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 9; }
__attribute__((noinline)) int f10(const char* x) { static const char* t = "magna aliqua aliqua sit robot mission adipiscing mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 10; }
__attribute__((noinline)) int f11(const char* x) { static const char* t = "sed do sit dolor et options mission et dolor tempor loading dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 11; }
__attribute__((noinline)) int f12(const char* x) { static const char* t = "amet lorem do ut moon ut options sit ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 12; }
__attribute__((noinline)) int f13(const char* x) { static const char* t = "monster moon ipsum incididunt robot aliqua eiusmod magna sed dolore elit ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 13; }
__attribute__((noinline)) int f14(const char* x) { static const char* t = "lorem dolor sit monster magna ipsum adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 14; }
__attribute__((noinline)) int f15(const char* x) { static const char* t = "do monster sed amet robot ipsum options eiusmod eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 15; }
__attribute__((noinline)) int f16(const char* x) { static const char* t = "amet options incididunt incididunt labore options dolore incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 16; }
__attribute__((noinline)) int f17(const char* x) { static const char* t = "rescue magna sit monster loading dolore sed ut mission planet robot elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 17; }
__attribute__((noinline)) int f18(const char* x) { static const char* t = "ut sed dolore do magna eiusmod lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 18; }
__attribute__((noinline)) int f19(const char* x) { static const char* t = "aliqua eiusmod lorem incididunt monster aliqua mission amet ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 19; }
__attribute__((noinline)) int f20(const char* x) { static const char* t = "labore tempor rescue tempor monster robot sed planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 20; }
__attribute__((noinline)) int f21(const char* x) { static const char* t = "lorem aliqua ipsum rescue lorem tempor sed mission labore do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 21; }
__attribute__((noinline)) int f22(const char* x) { static const char* t = "monster eiusmod consectetur tempor consectetur eiusmod moon tempor options monster sed do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 22; }
__attribute__((noinline)) int f23(const char* x) { static const char* t = "sit moon level lorem aliqua rescue planet amet do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 23; }
__attribute__((noinline)) int f24(const char* x) { static const char* t = "elit mission loading sed elit eiusmod consectetur rescue ut mission robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 24; }
__attribute__((noinline)) int f25(const char* x) { static const char* t = "sit monster eiusmod eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 25; }
__attribute__((noinline)) int f26(const char* x) { static const char* t = "labore loading options consectetur dolor eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 26; }
__attribute__((noinline)) int f27(const char* x) { static const char* t = "aliqua labore sed elit loading sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 27; }
__attribute__((noinline)) int f28(const char* x) { static const char* t = "dolore adipiscing eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 28; }
__attribute__((noinline)) int f29(const char* x) { static const char* t = "consectetur options sed eiusmod loading level mission dolor loading monster tempor aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 29; }
__attribute__((noinline)) int f30(const char* x) { static const char* t = "ut do dolore loading options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 30; }
__attribute__((noinline)) int f31(const char* x) { static const char* t = "labore tempor mission ut do ut aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 31; }
__attribute__((noinline)) int f32(const char* x) { static const char* t = "ipsum ut amet adipiscing lorem et level monster dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 32; }
__attribute__((noinline)) int f33(const char* x) { static const char* t = "magna robot elit ipsum planet labore level moon rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 33; }
__attribute__((noinline)) int f34(const char* x) { static const char* t = "do magna eiusmod elit options dolor options aliqua do sit loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 34; }
__attribute__((noinline)) int f35(const char* x) { static const char* t = "ipsum ipsum loading robot dolore adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 35; }
__attribute__((noinline)) int f36(const char* x) { static const char* t = "aliqua ipsum lorem et planet sit consectetur dolore do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 36; }
__attribute__((noinline)) int f37(const char* x) { static const char* t = "rescue lorem dolore magna ut ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 37; }
__attribute__((noinline)) int f38(const char* x) { static const char* t = "sit eiusmod amet sed options magna et loading loading ipsum tempor elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 38; }
__attribute__((noinline)) int f39(const char* x) { static const char* t = "sit magna level sit consectetur elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 39; }
__attribute__((noinline)) int f40(const char* x) { static const char* t = "loading amet level lorem et mission aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 40; }
__attribute__((noinline)) int f41(const char* x) { static const char* t = "ipsum moon sed elit sed monster dolore dolore ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 41; }
__attribute__((noinline)) int f42(const char* x) { static const char* t = "et eiusmod moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 42; }
__attribute__((noinline)) int f43(const char* x) { static const char* t = "options ipsum moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 43; }
__attribute__((noinline)) int f44(const char* x) { static const char* t = "ipsum sit ipsum dolor et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 44; }
__attribute__((noinline)) int f45(const char* x) { static const char* t = "options robot dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 45; }
__attribute__((noinline)) int f46(const char* x) { static const char* t = "dolore et eiusmod consectetur eiusmod dolor tempor incididunt mission incididunt aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 46; }
__attribute__((noinline)) int f47(const char* x) { static const char* t = "tempor sed adipiscing eiusmod ut sit amet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 47; }
__attribute__((noinline)) int f48(const char* x) { static const char* t = "lorem robot planet incididunt loading dolor aliqua consectetur ipsum tempor labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 48; }
__attribute__((noinline)) int f49(const char* x) { static const char* t = "mission loading magna incididunt mission loading ipsum monster ut ipsum tempor mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 49; }
__attribute__((noinline)) int f50(const char* x) { static const char* t = "moon robot eiusmod ut robot ut labore lorem elit adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 50; }
__attribute__((noinline)) int f51(const char* x) { static const char* t = "sed robot aliqua dolor loading ut elit ut amet lorem eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 51; }
__attribute__((noinline)) int f52(const char* x) { static const char* t = "magna loading options sed sit labore robot sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 52; }
__attribute__((noinline)) int f53(const char* x) { static const char* t = "loading incididunt rescue sit planet eiusmod aliqua magna sit loading aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 53; }
__attribute__((noinline)) int f54(const char* x) { static const char* t = "et amet elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 54; }
__attribute__((noinline)) int f55(const char* x) { static const char* t = "ipsum dolore dolor aliqua sit rescue incididunt consectetur level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 55; }
__attribute__((noinline)) int f56(const char* x) { static const char* t = "eiusmod level options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 56; }
__attribute__((noinline)) int f57(const char* x) { static const char* t = "lorem options sit rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 57; }
__attribute__((noinline)) int f58(const char* x) { static const char* t = "level robot do aliqua do loading dolor ipsum moon aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 58; }
__attribute__((noinline)) int f59(const char* x) { static const char* t = "dolore robot elit sit magna planet sit magna ipsum magna eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 59; }
__attribute__((noinline)) int f60(const char* x) { static const char* t = "consectetur level dolor elit consectetur mission elit labore monster robot moon incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 60; }
__attribute__((noinline)) int f61(const char* x) { static const char* t = "tempor monster incididunt tempor magna ut dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 61; }
__attribute__((noinline)) int f62(const char* x) { static const char* t = "dolore elit ut level planet consectetur ut robot aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 62; }
__attribute__((noinline)) int f63(const char* x) { static const char* t = "rescue dolore rescue et amet mission incididunt amet consectetur sit et planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 63; }
__attribute__((noinline)) int f64(const char* x) { static const char* t = "robot dolore labore aliqua planet options consectetur amet sed moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 64; }
__attribute__((noinline)) int f65(const char* x) { static const char* t = "amet aliqua dolore eiusmod elit options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 65; }
__attribute__((noinline)) int f66(const char* x) { static const char* t = "moon do rescue robot options ut monster options aliqua aliqua sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 66; }
__attribute__((noinline)) int f67(const char* x) { static const char* t = "do lorem sed et loading incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 67; }
__attribute__((noinline)) int f68(const char* x) { static const char* t = "consectetur aliqua tempor elit eiusmod et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 68; }
__attribute__((noinline)) int f69(const char* x) { static const char* t = "ut robot et robot monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 69; }
__attribute__((noinline)) int f70(const char* x) { static const char* t = "labore aliqua level level mission magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 70; }
__attribute__((noinline)) int f71(const char* x) { static const char* t = "et planet dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 71; }
__attribute__((noinline)) int f72(const char* x) { static const char* t = "loading planet ipsum labore elit elit mission robot moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 72; }
__attribute__((noinline)) int f73(const char* x) { static const char* t = "adipiscing options sed elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 73; }
__attribute__((noinline)) int f74(const char* x) { static const char* t = "moon sed amet consectetur monster robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 74; }
__attribute__((noinline)) int f75(const char* x) { static const char* t = "sed consectetur options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 75; }
__attribute__((noinline)) int f76(const char* x) { static const char* t = "eiusmod consectetur ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 76; }
__attribute__((noinline)) int f77(const char* x) { static const char* t = "planet loading dolor sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 77; }
__attribute__((noinline)) int f78(const char* x) { static const char* t = "sed level do ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 78; }
__attribute__((noinline)) int f79(const char* x) { static const char* t = "labore aliqua planet rescue eiusmod lorem lorem eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 79; }
__attribute__((noinline)) int f80(const char* x) { static const char* t = "ut incididunt et dolor adipiscing mission aliqua planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 80; }
__attribute__((noinline)) int f81(const char* x) { static const char* t = "incididunt amet magna eiusmod sit sed dolor rescue ut sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 81; }
__attribute__((noinline)) int f82(const char* x) { static const char* t = "dolore sed sit dolore robot tempor rescue moon tempor moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 82; }
__attribute__((noinline)) int f83(const char* x) { static const char* t = "do rescue rescue rescue mission loading level sed sit moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 83; }
__attribute__((noinline)) int f84(const char* x) { static const char* t = "rescue aliqua magna dolore sit rescue et dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 84; }
__attribute__((noinline)) int f85(const char* x) { static const char* t = "ipsum robot do rescue planet aliqua planet consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 85; }
__attribute__((noinline)) int f86(const char* x) { static const char* t = "consectetur tempor mission labore sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 86; }
__attribute__((noinline)) int f87(const char* x) { static const char* t = "magna amet eiusmod mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 87; }
__attribute__((noinline)) int f88(const char* x) { static const char* t = "ut magna do mission consectetur labore et do loading consectetur robot dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 88; }
__attribute__((noinline)) int f89(const char* x) { static const char* t = "robot consectetur moon magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 89; }
__attribute__((noinline)) int f90(const char* x) { static const char* t = "aliqua planet incididunt tempor sit sed sed incididunt ipsum options amet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 90; }
__attribute__((noinline)) int f91(const char* x) { static const char* t = "et dolore sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 91; }
__attribute__((noinline)) int f92(const char* x) { static const char* t = "robot moon dolore tempor eiusmod incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 92; }
__attribute__((noinline)) int f93(const char* x) { static const char* t = "magna loading moon dolor tempor et options sit amet sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 93; }
__attribute__((noinline)) int f94(const char* x) { static const char* t = "sit rescue sit aliqua moon planet sit consectetur robot adipiscing aliqua ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 94; }
__attribute__((noinline)) int f95(const char* x) { static const char* t = "level planet amet aliqua monster amet options incididunt loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 95; }
__attribute__((noinline)) int f96(const char* x) { static const char* t = "magna dolore consectetur aliqua consectetur adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 96; }
__attribute__((noinline)) int f97(const char* x) { static const char* t = "tempor loading do lorem level loading labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 97; }
__attribute__((noinline)) int f98(const char* x) { static const char* t = "level incididunt eiusmod magna aliqua do mission et dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 98; }
__attribute__((noinline)) int f99(const char* x) { static const char* t = "options rescue et lorem monster adipiscing planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 99; }
__attribute__((noinline)) int f100(const char* x) { static const char* t = "sit moon moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 100; }
__attribute__((noinline)) int f101(const char* x) { static const char* t = "et consectetur dolore mission labore adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 101; }
__attribute__((noinline)) int f102(const char* x) { static const char* t = "loading dolore adipiscing ipsum level dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 102; }
__attribute__((noinline)) int f103(const char* x) { static const char* t = "sit aliqua do rescue amet amet labore loading dolor monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 103; }
__attribute__((noinline)) int f104(const char* x) { static const char* t = "lorem tempor monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 104; }
__attribute__((noinline)) int f105(const char* x) { static const char* t = "dolore dolor et magna lorem eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 105; }
__attribute__((noinline)) int f106(const char* x) { static const char* t = "eiusmod options tempor robot robot amet dolor options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 106; }
__attribute__((noinline)) int f107(const char* x) { static const char* t = "moon ipsum robot dolor planet eiusmod loading adipiscing dolor options adipiscing ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 107; }
__attribute__((noinline)) int f108(const char* x) { static const char* t = "et eiusmod sit loading ipsum ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 108; }
__attribute__((noinline)) int f109(const char* x) { static const char* t = "options adipiscing robot consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 109; }
__attribute__((noinline)) int f110(const char* x) { static const char* t = "et et robot dolor magna options ut adipiscing mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 110; }
__attribute__((noinline)) int f111(const char* x) { static const char* t = "do lorem labore labore moon robot incididunt labore consectetur labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 111; }
__attribute__((noinline)) int f112(const char* x) { static const char* t = "planet sed tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 112; }
__attribute__((noinline)) int f113(const char* x) { static const char* t = "labore dolore tempor monster incididunt elit lorem loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 113; }
__attribute__((noinline)) int f114(const char* x) { static const char* t = "sed loading tempor amet options labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 114; }
__attribute__((noinline)) int f115(const char* x) { static const char* t = "adipiscing consectetur adipiscing lorem consectetur aliqua incididunt dolore consectetur mission lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 115; }
__attribute__((noinline)) int f116(const char* x) { static const char* t = "sit monster consectetur labore et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 116; }
__attribute__((noinline)) int f117(const char* x) { static const char* t = "ipsum level lorem incididunt labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 117; }
__attribute__((noinline)) int f118(const char* x) { static const char* t = "ut ipsum robot robot ipsum elit incididunt ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 118; }
__attribute__((noinline)) int f119(const char* x) { static const char* t = "et lorem elit elit sit incididunt et adipiscing consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 119; }
__attribute__((noinline)) int f120(const char* x) { static const char* t = "monster sit tempor sit monster ipsum loading planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 120; }
__attribute__((noinline)) int f121(const char* x) { static const char* t = "sed loading labore loading do et elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 121; }
__attribute__((noinline)) int f122(const char* x) { static const char* t = "sed lorem level eiusmod mission tempor eiusmod dolor ipsum rescue ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 122; }
__attribute__((noinline)) int f123(const char* x) { static const char* t = "aliqua monster lorem sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 123; }
__attribute__((noinline)) int f124(const char* x) { static const char* t = "rescue dolor lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 124; }
__attribute__((noinline)) int f125(const char* x) { static const char* t = "dolore ipsum et ipsum adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 125; }
__attribute__((noinline)) int f126(const char* x) { static const char* t = "eiusmod adipiscing moon et eiusmod loading et tempor rescue ipsum incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 126; }
__attribute__((noinline)) int f127(const char* x) { static const char* t = "moon monster mission incididunt dolor do consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 127; }
__attribute__((noinline)) int f128(const char* x) { static const char* t = "sit dolore incididunt magna eiusmod magna rescue moon incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 128; }
__attribute__((noinline)) int f129(const char* x) { static const char* t = "level planet options planet incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 129; }
__attribute__((noinline)) int f130(const char* x) { static const char* t = "tempor consectetur tempor loading ut labore elit labore moon robot et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 130; }
__attribute__((noinline)) int f131(const char* x) { static const char* t = "sed level consectetur dolore planet moon monster robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 131; }
__attribute__((noinline)) int f132(const char* x) { static const char* t = "et ipsum amet consectetur robot moon lorem level labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 132; }
__attribute__((noinline)) int f133(const char* x) { static const char* t = "moon robot rescue rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 133; }
__attribute__((noinline)) int f134(const char* x) { static const char* t = "eiusmod elit monster level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 134; }
__attribute__((noinline)) int f135(const char* x) { static const char* t = "monster options ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 135; }
__attribute__((noinline)) int f136(const char* x) { static const char* t = "labore options planet mission eiusmod tempor lorem dolor adipiscing incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 136; }
__attribute__((noinline)) int f137(const char* x) { static const char* t = "eiusmod aliqua do sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 137; }
__attribute__((noinline)) int f138(const char* x) { static const char* t = "dolor level mission adipiscing elit robot ipsum amet mission amet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 138; }
__attribute__((noinline)) int f139(const char* x) { static const char* t = "lorem sit elit do adipiscing elit options magna dolore ut dolore moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 139; }
__attribute__((noinline)) int f140(const char* x) { static const char* t = "eiusmod loading magna loading adipiscing labore consectetur monster dolor ipsum level loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 140; }
__attribute__((noinline)) int f141(const char* x) { static const char* t = "monster lorem options sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 141; }
__attribute__((noinline)) int f142(const char* x) { static const char* t = "sed dolor sit labore incididunt elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 142; }
__attribute__((noinline)) int f143(const char* x) { static const char* t = "sit mission et moon rescue options robot tempor incididunt monster rescue labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 143; }
__attribute__((noinline)) int f144(const char* x) { static const char* t = "do level monster labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 144; }
__attribute__((noinline)) int f145(const char* x) { static const char* t = "adipiscing sit magna lorem labore do planet mission dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 145; }
__attribute__((noinline)) int f146(const char* x) { static const char* t = "tempor adipiscing et moon dolor magna rescue planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 146; }
__attribute__((noinline)) int f147(const char* x) { static const char* t = "ut loading mission dolor monster dolore adipiscing elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 147; }
__attribute__((noinline)) int f148(const char* x) { static const char* t = "level ipsum eiusmod elit ut labore dolor sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 148; }
__attribute__((noinline)) int f149(const char* x) { static const char* t = "eiusmod consectetur planet adipiscing planet adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 149; }
__attribute__((noinline)) int f150(const char* x) { static const char* t = "labore robot magna options ut tempor adipiscing monster ut et moon ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 150; }
__attribute__((noinline)) int f151(const char* x) { static const char* t = "aliqua ipsum do lorem consectetur sit lorem planet amet do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 151; }
__attribute__((noinline)) int f152(const char* x) { static const char* t = "dolore ipsum mission et ipsum adipiscing planet adipiscing sed et ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 152; }
__attribute__((noinline)) int f153(const char* x) { static const char* t = "tempor labore planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 153; }
__attribute__((noinline)) int f154(const char* x) { static const char* t = "planet loading do amet sit labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 154; }
__attribute__((noinline)) int f155(const char* x) { static const char* t = "ut labore dolor adipiscing amet et moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 155; }
__attribute__((noinline)) int f156(const char* x) { static const char* t = "incididunt loading mission tempor consectetur ut do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 156; }
__attribute__((noinline)) int f157(const char* x) { static const char* t = "et dolore magna elit tempor options do do lorem labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 157; }
__attribute__((noinline)) int f158(const char* x) { static const char* t = "tempor loading level do planet elit loading dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 158; }
__attribute__((noinline)) int f159(const char* x) { static const char* t = "lorem amet mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 159; }
__attribute__((noinline)) int f160(const char* x) { static const char* t = "amet magna lorem consectetur ipsum lorem adipiscing moon loading labore tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 160; }
__attribute__((noinline)) int f161(const char* x) { static const char* t = "magna ipsum et consectetur elit lorem sed ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 161; }
__attribute__((noinline)) int f162(const char* x) { static const char* t = "level ipsum monster magna loading sit labore do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 162; }
__attribute__((noinline)) int f163(const char* x) { static const char* t = "elit rescue loading et ut planet sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 163; }
__attribute__((noinline)) int f164(const char* x) { static const char* t = "ipsum lorem ut ipsum mission rescue consectetur moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 164; }
__attribute__((noinline)) int f165(const char* x) { static const char* t = "elit amet planet moon level loading ut dolore moon level eiusmod magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 165; }
__attribute__((noinline)) int f166(const char* x) { static const char* t = "sed lorem consectetur ipsum lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 166; }
__attribute__((noinline)) int f167(const char* x) { static const char* t = "mission ipsum level labore labore dolore rescue moon options level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 167; }
__attribute__((noinline)) int f168(const char* x) { static const char* t = "dolore ut tempor dolore mission consectetur do consectetur dolor rescue amet level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 168; }
__attribute__((noinline)) int f169(const char* x) { static const char* t = "sit ut moon tempor labore labore sed loading sed labore do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 169; }
__attribute__((noinline)) int f170(const char* x) { static const char* t = "amet aliqua eiusmod amet dolore ipsum ut et options elit level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 170; }
__attribute__((noinline)) int f171(const char* x) { static const char* t = "aliqua monster sed lorem eiusmod aliqua monster magna sit et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 171; }
__attribute__((noinline)) int f172(const char* x) { static const char* t = "sed loading robot moon sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 172; }
__attribute__((noinline)) int f173(const char* x) { static const char* t = "ut rescue dolor tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 173; }
__attribute__((noinline)) int f174(const char* x) { static const char* t = "dolore et moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 174; }
__attribute__((noinline)) int f175(const char* x) { static const char* t = "adipiscing do tempor consectetur mission incididunt level incididunt eiusmod ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 175; }
__attribute__((noinline)) int f176(const char* x) { static const char* t = "adipiscing ipsum eiusmod eiusmod monster incididunt magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 176; }
__attribute__((noinline)) int f177(const char* x) { static const char* t = "ipsum amet ut sed ut dolor et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 177; }
__attribute__((noinline)) int f178(const char* x) { static const char* t = "adipiscing planet dolor robot dolore sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 178; }
__attribute__((noinline)) int f179(const char* x) { static const char* t = "mission level level lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 179; }
__attribute__((noinline)) int f180(const char* x) { static const char* t = "robot dolor ut sed et labore sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 180; }
__attribute__((noinline)) int f181(const char* x) { static const char* t = "magna magna ipsum consectetur elit et consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 181; }
__attribute__((noinline)) int f182(const char* x) { static const char* t = "amet robot consectetur robot labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 182; }
__attribute__((noinline)) int f183(const char* x) { static const char* t = "mission lorem amet incididunt ipsum consectetur moon mission consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 183; }
__attribute__((noinline)) int f184(const char* x) { static const char* t = "adipiscing mission level amet options amet ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 184; }
__attribute__((noinline)) int f185(const char* x) { static const char* t = "amet magna adipiscing incididunt moon sit ut incididunt consectetur lorem sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 185; }
__attribute__((noinline)) int f186(const char* x) { static const char* t = "amet sit amet do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 186; }
__attribute__((noinline)) int f187(const char* x) { static const char* t = "incididunt tempor monster dolor adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 187; }
__attribute__((noinline)) int f188(const char* x) { static const char* t = "tempor amet et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 188; }
__attribute__((noinline)) int f189(const char* x) { static const char* t = "dolor tempor magna et sit robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 189; }
__attribute__((noinline)) int f190(const char* x) { static const char* t = "et lorem planet tempor dolore planet options loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 190; }
__attribute__((noinline)) int f191(const char* x) { static const char* t = "aliqua ut labore magna magna do labore amet magna labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 191; }
__attribute__((noinline)) int f192(const char* x) { static const char* t = "adipiscing moon monster do planet options planet consectetur do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 192; }
__attribute__((noinline)) int f193(const char* x) { static const char* t = "eiusmod sed level adipiscing amet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 193; }
__attribute__((noinline)) int f194(const char* x) { static const char* t = "monster ipsum ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 194; }
__attribute__((noinline)) int f195(const char* x) { static const char* t = "options consectetur sit aliqua lorem consectetur options sit loading incididunt aliqua rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 195; }
__attribute__((noinline)) int f196(const char* x) { static const char* t = "dolore robot moon sed dolor labore magna aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 196; }
__attribute__((noinline)) int f197(const char* x) { static const char* t = "eiusmod amet aliqua monster adipiscing eiusmod labore dolore aliqua tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 197; }
__attribute__((noinline)) int f198(const char* x) { static const char* t = "aliqua tempor robot monster moon planet tempor options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 198; }
__attribute__((noinline)) int f199(const char* x) { static const char* t = "do do sed consectetur sit monster dolore elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 199; }
__attribute__((noinline)) int f200(const char* x) { static const char* t = "planet mission elit do ut sed labore amet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 200; }
__attribute__((noinline)) int f201(const char* x) { static const char* t = "eiusmod magna loading options consectetur monster dolore dolore labore monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 201; }
__attribute__((noinline)) int f202(const char* x) { static const char* t = "dolor ut ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 202; }
__attribute__((noinline)) int f203(const char* x) { static const char* t = "options monster moon do ipsum elit options incididunt incididunt adipiscing dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 203; }
__attribute__((noinline)) int f204(const char* x) { static const char* t = "dolore adipiscing ipsum magna et sit ut planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 204; }
__attribute__((noinline)) int f205(const char* x) { static const char* t = "robot magna tempor lorem do tempor dolore tempor incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 205; }
__attribute__((noinline)) int f206(const char* x) { static const char* t = "tempor mission rescue sit aliqua et amet eiusmod elit lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 206; }
__attribute__((noinline)) int f207(const char* x) { static const char* t = "dolor monster lorem amet dolor adipiscing eiusmod ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 207; }
__attribute__((noinline)) int f208(const char* x) { static const char* t = "adipiscing lorem lorem magna planet eiusmod magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 208; }
__attribute__((noinline)) int f209(const char* x) { static const char* t = "planet tempor level planet level loading adipiscing labore eiusmod rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 209; }
__attribute__((noinline)) int f210(const char* x) { static const char* t = "sit dolore incididunt elit et amet do do magna adipiscing sit level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 210; }
__attribute__((noinline)) int f211(const char* x) { static const char* t = "monster dolor ut lorem loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 211; }
__attribute__((noinline)) int f212(const char* x) { static const char* t = "incididunt lorem et level consectetur et sed amet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 212; }
__attribute__((noinline)) int f213(const char* x) { static const char* t = "adipiscing dolore mission ut aliqua mission rescue do ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 213; }
__attribute__((noinline)) int f214(const char* x) { static const char* t = "sit mission planet robot dolor dolor labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 214; }
__attribute__((noinline)) int f215(const char* x) { static const char* t = "dolor options lorem eiusmod et ut mission sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 215; }
__attribute__((noinline)) int f216(const char* x) { static const char* t = "mission ut aliqua elit eiusmod adipiscing mission incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 216; }
__attribute__((noinline)) int f217(const char* x) { static const char* t = "ipsum mission dolore lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 217; }
__attribute__((noinline)) int f218(const char* x) { static const char* t = "dolore elit aliqua level dolor consectetur elit level et level options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 218; }
__attribute__((noinline)) int f219(const char* x) { static const char* t = "incididunt do tempor labore rescue dolore elit adipiscing aliqua do eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 219; }
__attribute__((noinline)) int f220(const char* x) { static const char* t = "amet aliqua magna tempor monster dolore tempor eiusmod moon options aliqua options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 220; }
__attribute__((noinline)) int f221(const char* x) { static const char* t = "adipiscing labore ipsum planet ut options do mission adipiscing et options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 221; }
__attribute__((noinline)) int f222(const char* x) { static const char* t = "consectetur level sit labore sit dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 222; }
__attribute__((noinline)) int f223(const char* x) { static const char* t = "level adipiscing eiusmod consectetur moon ipsum eiusmod et elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 223; }
__attribute__((noinline)) int f224(const char* x) { static const char* t = "options rescue level planet ipsum elit incididunt tempor incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 224; }
__attribute__((noinline)) int f225(const char* x) { static const char* t = "consectetur do sed tempor sed ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 225; }
__attribute__((noinline)) int f226(const char* x) { static const char* t = "planet sit adipiscing elit do labore consectetur aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 226; }
__attribute__((noinline)) int f227(const char* x) { static const char* t = "elit et robot adipiscing adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 227; }
__attribute__((noinline)) int f228(const char* x) { static const char* t = "monster elit consectetur rescue moon dolore incididunt monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 228; }
__attribute__((noinline)) int f229(const char* x) { static const char* t = "ut monster consectetur mission do labore tempor ipsum dolor loading magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 229; }
__attribute__((noinline)) int f230(const char* x) { static const char* t = "et lorem aliqua consectetur sed dolore ut rescue et elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 230; }
__attribute__((noinline)) int f231(const char* x) { static const char* t = "level dolore et tempor incididunt monster et moon consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 231; }
__attribute__((noinline)) int f232(const char* x) { static const char* t = "robot ut eiusmod options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 232; }
__attribute__((noinline)) int f233(const char* x) { static const char* t = "aliqua eiusmod sit tempor dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 233; }
__attribute__((noinline)) int f234(const char* x) { static const char* t = "options do et mission magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 234; }
__attribute__((noinline)) int f235(const char* x) { static const char* t = "options labore tempor et ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 235; }
__attribute__((noinline)) int f236(const char* x) { static const char* t = "tempor level mission adipiscing monster dolor robot moon magna aliqua do aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 236; }
__attribute__((noinline)) int f237(const char* x) { static const char* t = "magna eiusmod ut level planet mission do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 237; }
__attribute__((noinline)) int f238(const char* x) { static const char* t = "ut rescue magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 238; }
__attribute__((noinline)) int f239(const char* x) { static const char* t = "ut et tempor aliqua consectetur elit do robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 239; }
__attribute__((noinline)) int f240(const char* x) { static const char* t = "aliqua level incididunt robot sit eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 240; }
__attribute__((noinline)) int f241(const char* x) { static const char* t = "consectetur eiusmod planet et consectetur magna incididunt labore adipiscing ut magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 241; }
__attribute__((noinline)) int f242(const char* x) { static const char* t = "tempor sit planet ipsum monster et robot adipiscing consectetur dolore rescue consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 242; }
__attribute__((noinline)) int f243(const char* x) { static const char* t = "sit magna magna sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 243; }
__attribute__((noinline)) int f244(const char* x) { static const char* t = "options magna dolore eiusmod incididunt sed dolor et sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 244; }
__attribute__((noinline)) int f245(const char* x) { static const char* t = "elit sed sit adipiscing sit et tempor ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 245; }
__attribute__((noinline)) int f246(const char* x) { static const char* t = "sed tempor rescue consectetur sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 246; }
__attribute__((noinline)) int f247(const char* x) { static const char* t = "moon dolore adipiscing rescue elit elit sed loading tempor planet eiusmod sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 247; }
__attribute__((noinline)) int f248(const char* x) { static const char* t = "options robot amet moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 248; }
__attribute__((noinline)) int f249(const char* x) { static const char* t = "elit labore eiusmod sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 249; }
__attribute__((noinline)) int f250(const char* x) { static const char* t = "level moon amet consectetur ipsum rescue et sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 250; }
__attribute__((noinline)) int f251(const char* x) { static const char* t = "amet tempor options labore planet ut dolore aliqua rescue aliqua ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 251; }
__attribute__((noinline)) int f252(const char* x) { static const char* t = "sed do magna sed aliqua incididunt amet ipsum ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 252; }
__attribute__((noinline)) int f253(const char* x) { static const char* t = "ut mission lorem adipiscing loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 253; }
__attribute__((noinline)) int f254(const char* x) { static const char* t = "dolore planet adipiscing options robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 254; }
__attribute__((noinline)) int f255(const char* x) { static const char* t = "sed ipsum mission magna aliqua planet tempor adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 255; }
__attribute__((noinline)) int f256(const char* x) { static const char* t = "consectetur adipiscing planet dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 256; }
__attribute__((noinline)) int f257(const char* x) { static const char* t = "ut planet do amet sit magna eiusmod rescue level monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 257; }
__attribute__((noinline)) int f258(const char* x) { static const char* t = "sed amet dolor monster dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 258; }
__attribute__((noinline)) int f259(const char* x) { static const char* t = "sit lorem robot dolor mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 259; }
__attribute__((noinline)) int f260(const char* x) { static const char* t = "incididunt robot labore magna rescue monster labore sed consectetur robot level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 260; }
__attribute__((noinline)) int f261(const char* x) { static const char* t = "dolor do rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 261; }
__attribute__((noinline)) int f262(const char* x) { static const char* t = "consectetur lorem ipsum eiusmod dolore planet eiusmod level tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 262; }
__attribute__((noinline)) int f263(const char* x) { static const char* t = "ipsum loading adipiscing incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 263; }
__attribute__((noinline)) int f264(const char* x) { static const char* t = "loading magna labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 264; }
__attribute__((noinline)) int f265(const char* x) { static const char* t = "mission elit labore labore elit loading lorem tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 265; }
__attribute__((noinline)) int f266(const char* x) { static const char* t = "elit consectetur ut incididunt sit incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 266; }
__attribute__((noinline)) int f267(const char* x) { static const char* t = "aliqua sit magna rescue monster elit do sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 267; }
__attribute__((noinline)) int f268(const char* x) { static const char* t = "incididunt lorem aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 268; }
__attribute__((noinline)) int f269(const char* x) { static const char* t = "elit adipiscing labore aliqua dolore sed mission moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 269; }
__attribute__((noinline)) int f270(const char* x) { static const char* t = "incididunt rescue planet adipiscing dolore aliqua ut mission do loading dolor consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 270; }
__attribute__((noinline)) int f271(const char* x) { static const char* t = "dolore dolore sit do aliqua monster amet labore dolore amet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 271; }
__attribute__((noinline)) int f272(const char* x) { static const char* t = "dolore consectetur elit tempor dolore do sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 272; }
__attribute__((noinline)) int f273(const char* x) { static const char* t = "et dolor et loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 273; }
__attribute__((noinline)) int f274(const char* x) { static const char* t = "planet moon ut lorem lorem lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 274; }
__attribute__((noinline)) int f275(const char* x) { static const char* t = "monster lorem ipsum robot dolore options et lorem ipsum tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 275; }
__attribute__((noinline)) int f276(const char* x) { static const char* t = "do level et et do moon do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 276; }
__attribute__((noinline)) int f277(const char* x) { static const char* t = "do mission aliqua dolor incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 277; }
__attribute__((noinline)) int f278(const char* x) { static const char* t = "sit rescue adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 278; }
__attribute__((noinline)) int f279(const char* x) { static const char* t = "dolor consectetur planet incididunt dolore planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 279; }
__attribute__((noinline)) int f280(const char* x) { static const char* t = "amet mission consectetur dolor rescue do dolore options dolore lorem et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 280; }
__attribute__((noinline)) int f281(const char* x) { static const char* t = "tempor rescue et dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 281; }
__attribute__((noinline)) int f282(const char* x) { static const char* t = "rescue robot eiusmod magna loading incididunt ut labore eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 282; }
__attribute__((noinline)) int f283(const char* x) { static const char* t = "lorem eiusmod do et planet mission sed loading et planet sed adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 283; }
__attribute__((noinline)) int f284(const char* x) { static const char* t = "sit mission sed planet et ut et moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 284; }
__attribute__((noinline)) int f285(const char* x) { static const char* t = "planet eiusmod monster ipsum rescue elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 285; }
__attribute__((noinline)) int f286(const char* x) { static const char* t = "ipsum monster incididunt elit incididunt consectetur eiusmod sit mission consectetur dolore labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 286; }
__attribute__((noinline)) int f287(const char* x) { static const char* t = "ut ut aliqua aliqua eiusmod incididunt ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 287; }
__attribute__((noinline)) int f288(const char* x) { static const char* t = "tempor planet level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 288; }
__attribute__((noinline)) int f289(const char* x) { static const char* t = "tempor planet incididunt sed dolore elit amet elit adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 289; }
__attribute__((noinline)) int f290(const char* x) { static const char* t = "lorem mission ut planet options sit monster moon incididunt et et incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 290; }
__attribute__((noinline)) int f291(const char* x) { static const char* t = "dolore magna ut monster adipiscing et incididunt ipsum mission magna robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 291; }
__attribute__((noinline)) int f292(const char* x) { static const char* t = "lorem adipiscing aliqua rescue loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 292; }
__attribute__((noinline)) int f293(const char* x) { static const char* t = "level amet incididunt moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 293; }
__attribute__((noinline)) int f294(const char* x) { static const char* t = "sit sit sit monster adipiscing do magna options amet ut ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 294; }
__attribute__((noinline)) int f295(const char* x) { static const char* t = "consectetur adipiscing robot level mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 295; }
__attribute__((noinline)) int f296(const char* x) { static const char* t = "et eiusmod mission labore dolore lorem sed magna lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 296; }
__attribute__((noinline)) int f297(const char* x) { static const char* t = "eiusmod eiusmod magna incididunt adipiscing sit do adipiscing dolor adipiscing incididunt elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 297; }
__attribute__((noinline)) int f298(const char* x) { static const char* t = "options eiusmod elit planet dolor eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 298; }
__attribute__((noinline)) int f299(const char* x) { static const char* t = "do moon adipiscing level magna adipiscing magna planet incididunt lorem dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 299; }
__attribute__((noinline)) int f300(const char* x) { static const char* t = "level level elit amet moon sed level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 300; }
__attribute__((noinline)) int f301(const char* x) { static const char* t = "dolor loading sed tempor adipiscing do amet tempor adipiscing adipiscing mission magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 301; }
__attribute__((noinline)) int f302(const char* x) { static const char* t = "labore ut sed ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 302; }
__attribute__((noinline)) int f303(const char* x) { static const char* t = "incididunt sed aliqua do level dolore adipiscing labore adipiscing do tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 303; }
__attribute__((noinline)) int f304(const char* x) { static const char* t = "sit ut moon incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 304; }
__attribute__((noinline)) int f305(const char* x) { static const char* t = "loading mission moon aliqua elit sed planet sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 305; }
__attribute__((noinline)) int f306(const char* x) { static const char* t = "aliqua sit lorem consectetur options eiusmod tempor monster consectetur elit eiusmod ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 306; }
__attribute__((noinline)) int f307(const char* x) { static const char* t = "moon eiusmod monster magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 307; }
__attribute__((noinline)) int f308(const char* x) { static const char* t = "ut eiusmod magna do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 308; }
__attribute__((noinline)) int f309(const char* x) { static const char* t = "et labore moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 309; }
__attribute__((noinline)) int f310(const char* x) { static const char* t = "moon consectetur et lorem sit loading consectetur tempor options options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 310; }
__attribute__((noinline)) int f311(const char* x) { static const char* t = "sed incididunt options dolore adipiscing options labore incididunt et tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 311; }
__attribute__((noinline)) int f312(const char* x) { static const char* t = "planet lorem magna eiusmod et aliqua et magna %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 312; }
__attribute__((noinline)) int f313(const char* x) { static const char* t = "lorem et dolor robot do consectetur elit magna sit rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 313; }
__attribute__((noinline)) int f314(const char* x) { static const char* t = "consectetur planet loading sed eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 314; }
__attribute__((noinline)) int f315(const char* x) { static const char* t = "tempor magna lorem level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 315; }
__attribute__((noinline)) int f316(const char* x) { static const char* t = "options eiusmod lorem monster ipsum incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 316; }
__attribute__((noinline)) int f317(const char* x) { static const char* t = "sit mission moon dolore labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 317; }
__attribute__((noinline)) int f318(const char* x) { static const char* t = "planet et loading lorem labore rescue ut mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 318; }
__attribute__((noinline)) int f319(const char* x) { static const char* t = "planet dolor sit moon dolor rescue dolor adipiscing level sit sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 319; }
__attribute__((noinline)) int f320(const char* x) { static const char* t = "rescue eiusmod lorem loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 320; }
__attribute__((noinline)) int f321(const char* x) { static const char* t = "ipsum robot labore ipsum sit dolore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 321; }
__attribute__((noinline)) int f322(const char* x) { static const char* t = "eiusmod robot labore planet monster do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 322; }
__attribute__((noinline)) int f323(const char* x) { static const char* t = "robot lorem options adipiscing robot magna mission lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 323; }
__attribute__((noinline)) int f324(const char* x) { static const char* t = "moon aliqua ut amet robot options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 324; }
__attribute__((noinline)) int f325(const char* x) { static const char* t = "labore dolore dolore ut rescue et amet monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 325; }
__attribute__((noinline)) int f326(const char* x) { static const char* t = "options mission do dolor elit moon consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 326; }
__attribute__((noinline)) int f327(const char* x) { static const char* t = "eiusmod labore loading incididunt elit dolore robot magna eiusmod do eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 327; }
__attribute__((noinline)) int f328(const char* x) { static const char* t = "moon moon moon consectetur do tempor dolor consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 328; }
__attribute__((noinline)) int f329(const char* x) { static const char* t = "planet do monster labore incididunt dolore ut level adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 329; }
__attribute__((noinline)) int f330(const char* x) { static const char* t = "mission tempor lorem monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 330; }
__attribute__((noinline)) int f331(const char* x) { static const char* t = "labore ipsum mission mission labore dolore rescue level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 331; }
__attribute__((noinline)) int f332(const char* x) { static const char* t = "sed monster et magna dolore planet et moon level planet adipiscing options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 332; }
__attribute__((noinline)) int f333(const char* x) { static const char* t = "dolor options robot dolor level et loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 333; }
__attribute__((noinline)) int f334(const char* x) { static const char* t = "incididunt robot consectetur adipiscing options sed robot amet magna aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 334; }
__attribute__((noinline)) int f335(const char* x) { static const char* t = "lorem consectetur adipiscing mission elit labore rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 335; }
__attribute__((noinline)) int f336(const char* x) { static const char* t = "sit do tempor rescue adipiscing level dolore rescue sit lorem eiusmod labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 336; }
__attribute__((noinline)) int f337(const char* x) { static const char* t = "et monster ipsum loading mission eiusmod loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 337; }
__attribute__((noinline)) int f338(const char* x) { static const char* t = "consectetur mission labore aliqua aliqua et do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 338; }
__attribute__((noinline)) int f339(const char* x) { static const char* t = "et eiusmod elit dolor adipiscing magna ipsum tempor magna dolor tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 339; }
__attribute__((noinline)) int f340(const char* x) { static const char* t = "consectetur ipsum et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 340; }
__attribute__((noinline)) int f341(const char* x) { static const char* t = "eiusmod sit consectetur options tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 341; }
__attribute__((noinline)) int f342(const char* x) { static const char* t = "level elit et robot dolore mission magna ipsum lorem moon magna elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 342; }
__attribute__((noinline)) int f343(const char* x) { static const char* t = "amet aliqua do magna elit tempor options loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 343; }
__attribute__((noinline)) int f344(const char* x) { static const char* t = "aliqua incididunt amet labore ut rescue robot incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 344; }
__attribute__((noinline)) int f345(const char* x) { static const char* t = "labore incididunt level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 345; }
__attribute__((noinline)) int f346(const char* x) { static const char* t = "mission robot moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 346; }
__attribute__((noinline)) int f347(const char* x) { static const char* t = "dolor sed ut do tempor sit lorem consectetur loading loading sit ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 347; }
__attribute__((noinline)) int f348(const char* x) { static const char* t = "incididunt robot ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 348; }
__attribute__((noinline)) int f349(const char* x) { static const char* t = "rescue dolor options ut ipsum sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 349; }
__attribute__((noinline)) int f350(const char* x) { static const char* t = "consectetur ut rescue tempor ut planet lorem elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 350; }
__attribute__((noinline)) int f351(const char* x) { static const char* t = "tempor dolore elit planet level incididunt tempor robot tempor do monster consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 351; }
__attribute__((noinline)) int f352(const char* x) { static const char* t = "tempor planet lorem elit mission consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 352; }
__attribute__((noinline)) int f353(const char* x) { static const char* t = "sed adipiscing amet aliqua options et moon dolore aliqua level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 353; }
__attribute__((noinline)) int f354(const char* x) { static const char* t = "consectetur moon level incididunt level sed incididunt moon aliqua incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 354; }
__attribute__((noinline)) int f355(const char* x) { static const char* t = "adipiscing incididunt mission sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 355; }
__attribute__((noinline)) int f356(const char* x) { static const char* t = "options moon rescue aliqua tempor level %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 356; }
__attribute__((noinline)) int f357(const char* x) { static const char* t = "sed do level robot rescue mission incididunt mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 357; }
__attribute__((noinline)) int f358(const char* x) { static const char* t = "moon ut amet mission tempor dolore dolor do eiusmod monster moon %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 358; }
__attribute__((noinline)) int f359(const char* x) { static const char* t = "planet adipiscing adipiscing planet robot level incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 359; }
__attribute__((noinline)) int f360(const char* x) { static const char* t = "mission planet adipiscing dolore elit tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 360; }
__attribute__((noinline)) int f361(const char* x) { static const char* t = "sed labore elit mission moon sit planet sit dolore aliqua lorem rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 361; }
__attribute__((noinline)) int f362(const char* x) { static const char* t = "ut options options ipsum loading level monster magna aliqua do do monster %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 362; }
__attribute__((noinline)) int f363(const char* x) { static const char* t = "amet planet dolore amet sed consectetur loading et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 363; }
__attribute__((noinline)) int f364(const char* x) { static const char* t = "sed dolore elit consectetur rescue options aliqua moon loading %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 364; }
__attribute__((noinline)) int f365(const char* x) { static const char* t = "dolor adipiscing level tempor lorem aliqua rescue et options ipsum %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 365; }
__attribute__((noinline)) int f366(const char* x) { static const char* t = "ut ut sit monster incididunt eiusmod ut level do tempor mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 366; }
__attribute__((noinline)) int f367(const char* x) { static const char* t = "incididunt options dolor labore adipiscing dolor rescue sed labore moon planet sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 367; }
__attribute__((noinline)) int f368(const char* x) { static const char* t = "magna dolor options elit aliqua magna tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 368; }
__attribute__((noinline)) int f369(const char* x) { static const char* t = "moon mission level elit aliqua rescue mission %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 369; }
__attribute__((noinline)) int f370(const char* x) { static const char* t = "options ut ipsum dolor aliqua lorem amet adipiscing %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 370; }
__attribute__((noinline)) int f371(const char* x) { static const char* t = "elit mission loading sit adipiscing tempor consectetur magna moon dolor consectetur incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 371; }
__attribute__((noinline)) int f372(const char* x) { static const char* t = "labore lorem sit level eiusmod adipiscing incididunt loading ut moon elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 372; }
__attribute__((noinline)) int f373(const char* x) { static const char* t = "ipsum dolor robot dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 373; }
__attribute__((noinline)) int f374(const char* x) { static const char* t = "planet do rescue level options adipiscing consectetur labore consectetur dolor robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 374; }
__attribute__((noinline)) int f375(const char* x) { static const char* t = "dolor et dolore rescue amet amet elit elit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 375; }
__attribute__((noinline)) int f376(const char* x) { static const char* t = "sed incididunt rescue ipsum options elit monster do level rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 376; }
__attribute__((noinline)) int f377(const char* x) { static const char* t = "dolor mission consectetur consectetur mission monster lorem labore %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 377; }
__attribute__((noinline)) int f378(const char* x) { static const char* t = "moon loading elit sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 378; }
__attribute__((noinline)) int f379(const char* x) { static const char* t = "level amet magna eiusmod robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 379; }
__attribute__((noinline)) int f380(const char* x) { static const char* t = "magna moon ut lorem do dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 380; }
__attribute__((noinline)) int f381(const char* x) { static const char* t = "elit dolore labore elit sit incididunt options aliqua mission planet %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 381; }
__attribute__((noinline)) int f382(const char* x) { static const char* t = "consectetur elit rescue dolore sed sit amet labore loading options loading ut %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 382; }
__attribute__((noinline)) int f383(const char* x) { static const char* t = "monster incididunt sit %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 383; }
__attribute__((noinline)) int f384(const char* x) { static const char* t = "magna ut options planet consectetur dolor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 384; }
__attribute__((noinline)) int f385(const char* x) { static const char* t = "et lorem loading consectetur %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 385; }
__attribute__((noinline)) int f386(const char* x) { static const char* t = "eiusmod level monster level eiusmod et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 386; }
__attribute__((noinline)) int f387(const char* x) { static const char* t = "do dolor level sit loading tempor aliqua aliqua ipsum lorem %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 387; }
__attribute__((noinline)) int f388(const char* x) { static const char* t = "eiusmod ipsum dolor consectetur sed sit lorem options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 388; }
__attribute__((noinline)) int f389(const char* x) { static const char* t = "rescue robot monster et mission lorem options %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 389; }
__attribute__((noinline)) int f390(const char* x) { static const char* t = "robot incididunt ipsum sed eiusmod amet options magna tempor %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 390; }
__attribute__((noinline)) int f391(const char* x) { static const char* t = "mission planet dolor eiusmod loading aliqua %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 391; }
__attribute__((noinline)) int f392(const char* x) { static const char* t = "magna planet mission incididunt amet incididunt sed %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 392; }
__attribute__((noinline)) int f393(const char* x) { static const char* t = "robot aliqua adipiscing et %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 393; }
__attribute__((noinline)) int f394(const char* x) { static const char* t = "dolor incididunt do dolor monster options planet dolore magna moon eiusmod %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 394; }
__attribute__((noinline)) int f395(const char* x) { static const char* t = "adipiscing elit dolore planet aliqua incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 395; }
__attribute__((noinline)) int f396(const char* x) { static const char* t = "rescue mission do loading robot loading amet amet robot rescue %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 396; }
__attribute__((noinline)) int f397(const char* x) { static const char* t = "lorem elit consectetur dolore labore tempor planet robot ut aliqua loading incididunt %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 397; }
__attribute__((noinline)) int f398(const char* x) { static const char* t = "dolore magna do incididunt magna incididunt loading do dolor robot %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 398; }
__attribute__((noinline)) int f399(const char* x) { static const char* t = "monster planet eiusmod sit dolor incididunt monster ut sed robot labore do %d"; return (int)strlen(t) + (x ? (int)strlen(x) : 0) + 399; }
int (*table[])(const char*) = {f0,f1,f2,f3,f4,f5,f6,f7,f8,f9,f10,f11,f12,f13,f14,f15,f16,f17,f18,f19,f20,f21,f22,f23,f24,f25,f26,f27,f28,f29,f30,f31,f32,f33,f34,f35,f36,f37,f38,f39,f40,f41,f42,f43,f44,f45,f46,f47,f48,f49,f50,f51,f52,f53,f54,f55,f56,f57,f58,f59,f60,f61,f62,f63,f64,f65,f66,f67,f68,f69,f70,f71,f72,f73,f74,f75,f76,f77,f78,f79,f80,f81,f82,f83,f84,f85,f86,f87,f88,f89,f90,f91,f92,f93,f94,f95,f96,f97,f98,f99,f100,f101,f102,f103,f104,f105,f106,f107,f108,f109,f110,f111,f112,f113,f114,f115,f116,f117,f118,f119,f120,f121,f122,f123,f124,f125,f126,f127,f128,f129,f130,f131,f132,f133,f134,f135,f136,f137,f138,f139,f140,f141,f142,f143,f144,f145,f146,f147,f148,f149,f150,f151,f152,f153,f154,f155,f156,f157,f158,f159,f160,f161,f162,f163,f164,f165,f166,f167,f168,f169,f170,f171,f172,f173,f174,f175,f176,f177,f178,f179,f180,f181,f182,f183,f184,f185,f186,f187,f188,f189,f190,f191,f192,f193,f194,f195,f196,f197,f198,f199,f200,f201,f202,f203,f204,f205,f206,f207,f208,f209,f210,f211,f212,f213,f214,f215,f216,f217,f218,f219,f220,f221,f222,f223,f224,f225,f226,f227,f228,f229,f230,f231,f232,f233,f234,f235,f236,f237,f238,f239,f240,f241,f242,f243,f244,f245,f246,f247,f248,f249,f250,f251,f252,f253,f254,f255,f256,f257,f258,f259,f260,f261,f262,f263,f264,f265,f266,f267,f268,f269,f270,f271,f272,f273,f274,f275,f276,f277,f278,f279,f280,f281,f282,f283,f284,f285,f286,f287,f288,f289,f290,f291,f292,f293,f294,f295,f296,f297,f298,f299,f300,f301,f302,f303,f304,f305,f306,f307,f308,f309,f310,f311,f312,f313,f314,f315,f316,f317,f318,f319,f320,f321,f322,f323,f324,f325,f326,f327,f328,f329,f330,f331,f332,f333,f334,f335,f336,f337,f338,f339,f340,f341,f342,f343,f344,f345,f346,f347,f348,f349,f350,f351,f352,f353,f354,f355,f356,f357,f358,f359,f360,f361,f362,f363,f364,f365,f366,f367,f368,f369,f370,f371,f372,f373,f374,f375,f376,f377,f378,f379,f380,f381,f382,f383,f384,f385,f386,f387,f388,f389,f390,f391,f392,f393,f394,f395,f396,f397,f398,f399};
int main(int c, char** v) { int s=0; for (int i=0;i<400;i++) s+=table[i](c>1?v[1]:"hello monster"); printf("%d\n", s); return 0; }