cmake_minimum_required(VERSION 3.16)
project(vpaot LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()
option(ZYDIS_BUILD_TOOLS "" OFF)
option(ZYDIS_BUILD_EXAMPLES "" OFF)
option(ZYDIS_BUILD_DOXYGEN "" OFF)
option(ZYDIS_BUILD_MAN "" OFF)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/../../third_party/zydis zydis EXCLUDE_FROM_ALL)
add_executable(vpaot main.cpp image.cpp translate.cpp)
target_link_libraries(vpaot PRIVATE Zydis)
if(MSVC)
  target_compile_definitions(vpaot PRIVATE _CRT_SECURE_NO_WARNINGS)
else()
  target_compile_options(vpaot PRIVATE -Wall -Wextra)
endif()
