// SPDX-License-Identifier: GPL-2.0-or-later
//
// vpaot: ahead-of-time translation of an x86-64 program image into C.
//
//   vpaot --elf eboot.bin --out game.c [--stats report.json]
//   vpaot --raw code.bin --base 0x1000 --entry 0x1000 [--entry ...] --out test.c
//
// `--report` alone prints the coverage statistics (what the image needs that the translator
// does not do yet) without writing C.
#include "image.h"
#include "translate.h"

#include <cctype>
#include <cinttypes>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <stdexcept>

using namespace vpaot;

static void usage() {
    fprintf(stderr,
            "usage: vpaot (--elf FILE | --raw FILE --base ADDR) [--entry ADDR]... [--out FILE.c]\n"
            "             [--stats FILE.json] [--rip] [--trace] [--max-functions N] [--split FUNCTIONS_PER_FILE] [--native ADDR]... [--module NAME] [--pic]\n"
            "       vpaot --registry OUT.c MODULE...   (the file that links in a game's translated modules)\n"
            "             [--roots FILE]   extra entry points, one per line as an offset from the image base\n"
            "                              (\"0x1234\" or \"module+0x1234\", as the runtime logs missing entries: with --module,\n"
            "                              only that module's lines are taken; # comments)\n");
}

static void write_stats(const Stats& s, const std::string& path, size_t img_imports) {
    FILE* f = path.empty() ? stdout : fopen(path.c_str(), "w");
    if (!f) throw std::runtime_error("cannot write " + path);
    fprintf(f, "{\n  \"functions\": %" PRIu64 ",\n  \"instructions\": %" PRIu64 ",\n  \"unsupported\": %" PRIu64 ",\n",
            s.functions, s.instructions, s.unsupported);
    fprintf(f, "  \"indirect_calls\": %" PRIu64 ",\n  \"indirect_jumps\": %" PRIu64 ",\n  \"jump_tables\": %" PRIu64 ",\n", s.indirect_calls, s.indirect_jumps, s.jump_tables);
    fprintf(f, "  \"imports\": %zu,\n", img_imports);
    fprintf(f, "  \"supported_fraction\": %.4f,\n",
            s.instructions ? 1.0 - (double)s.unsupported / (double)s.instructions : 1.0);
    fprintf(f, "  \"unsupported_by_mnemonic\": {\n");
    bool first = true;
    for (auto& [k, v] : s.unsupported_by_mnemonic) {
        fprintf(f, "%s    \"%s\": %" PRIu64, first ? "" : ",\n", k.c_str(), v);
        first = false;
    }
    fprintf(f, "\n  },\n  \"unsupported_sites\": [\n");
    first = true;
    for (auto& [a, t] : s.unsupported_sites) {
        fprintf(f, "%s    [\"%#llx\", \"%s\"]", first ? "" : ",\n", (unsigned long long)a, t.c_str());
        first = false;
    }
    fprintf(f, "\n  ],\n  \"indirect_jump_sites\": [\n");
    first = true;
    for (auto& [a, t] : s.indirect_jump_sites) {
        fprintf(f, "%s    [\"%#llx\", \"%s\"]", first ? "" : ",\n", (unsigned long long)a, t.c_str());
        first = false;
    }
    fprintf(f, "\n  ],\n  \"by_mnemonic\": {\n");
    first = true;
    for (auto& [k, v] : s.by_mnemonic) {
        fprintf(f, "%s    \"%s\": %" PRIu64, first ? "" : ",\n", k.c_str(), v);
        first = false;
    }
    fprintf(f, "\n  }\n}\n");
    if (f != stdout) fclose(f);
}

// `vpaot --registry OUT.c MODULE...`: the C file that registers a game's translated modules by
// reference. A static library (shadPS4 on visionOS) only links the objects something refers to,
// so the engine calls vp_register_game_modules() and this file pulls every module in.
static int write_registry(int argc, char** argv) {
    if (argc < 3) { usage(); return 2; }
    FILE* f = fopen(argv[2], "w");
    if (!f) { fprintf(stderr, "vpaot: cannot write %s\n", argv[2]); return 1; }
    fprintf(f, "/* Generated by vpaot --registry. Do not edit. */\n#include \"vp_emit.h\"\n\n");
    for (int i = 3; i < argc; ++i) fprintf(f, "extern VpModule vp_module_%s;\n", argv[i]);
    fprintf(f, "\nvoid vp_register_game_modules(void) {\n");
    for (int i = 3; i < argc; ++i) fprintf(f, "    vp_register_module(&vp_module_%s);\n", argv[i]);
    fprintf(f, "}\n");
    fclose(f);
    fprintf(stderr, "vpaot: registry of %d modules in %s\n", argc - 3, argv[2]);
    return 0;
}

int main(int argc, char** argv) {
    if (argc >= 2 && !strcmp(argv[1], "--registry")) return write_registry(argc, argv);
    std::string elf, raw, out, stats_path;
    uint64_t base = 0;
    std::vector<uint64_t> entries;
    std::vector<std::string> roots_files;
    Options opt;
    for (int i = 1; i < argc; ++i) {
        auto next = [&]() -> const char* {
            if (i + 1 >= argc) { usage(); exit(2); }
            return argv[++i];
        };
        if (!strcmp(argv[i], "--elf")) elf = next();
        else if (!strcmp(argv[i], "--raw")) raw = next();
        else if (!strcmp(argv[i], "--base")) base = strtoull(next(), nullptr, 0);
        else if (!strcmp(argv[i], "--entry")) entries.push_back(strtoull(next(), nullptr, 0));
        else if (!strcmp(argv[i], "--out")) out = next();
        else if (!strcmp(argv[i], "--stats")) stats_path = next();
        else if (!strcmp(argv[i], "--rip")) opt.emit_rip_updates = true;
        else if (!strcmp(argv[i], "--trace")) opt.trace = true;
        else if (!strcmp(argv[i], "--max-functions")) opt.max_functions = strtoull(next(), nullptr, 0);
        else if (!strcmp(argv[i], "--regcache")) opt.regcache = true;
        else if (!strcmp(argv[i], "--scan-data")) opt.scan_data = true;
        else if (!strcmp(argv[i], "--pic")) opt.pic = true;
        else if (!strcmp(argv[i], "--no-regcache")) opt.regcache = false;
        else if (!strcmp(argv[i], "--no-lazy-flags")) opt.lazy_flags = false;
        else if (!strcmp(argv[i], "--no-resume-points")) opt.resume_points = false;
        else if (!strcmp(argv[i], "--module")) {
            opt.module = next();
            if (opt.module.empty() || isdigit((unsigned char)opt.module[0])) { fprintf(stderr, "vpaot: --module must be a C identifier\n"); return 2; }
            for (char ch : opt.module) {
                if (!isalnum((unsigned char)ch) && ch != '_') { fprintf(stderr, "vpaot: --module must be a C identifier\n"); return 2; }
            }
            opt.symbol_prefix = opt.module + "_fn_";
        }
        else if (!strcmp(argv[i], "--split")) opt.split = strtoull(next(), nullptr, 0);
        else if (!strcmp(argv[i], "--native")) opt.natives.insert(strtoull(next(), nullptr, 0));
        else if (!strcmp(argv[i], "--roots")) roots_files.push_back(next());
        else { usage(); return 2; }
    }
    if (elf.empty() == raw.empty()) { usage(); return 2; }
    try {
        Image img = raw.empty() ? load_elf_or_self(elf) : load_raw(raw, base);
        if (entries.empty()) entries.push_back(img.entry);
        for (const auto& path : roots_files) {
            FILE* rf = fopen(path.c_str(), "r");
            if (!rf) throw std::runtime_error("cannot read " + path);
            char buf[512];
            size_t added = 0;
            while (fgets(buf, sizeof buf, rf)) {
                char* p = buf;
                if (char* hash = strchr(p, '#')) *hash = 0;
                if (char* plus = strchr(p, '+')) {
                    // "module+0xOFF": only this module's lines (a log covers every module of a game).
                    char* name = p;
                    while (isspace((unsigned char)*name)) ++name;
                    const std::string mod(name, plus);
                    if (!opt.module.empty() && mod != opt.module) continue;
                    p = plus + 1;
                }
                while (*p && isspace((unsigned char)*p)) ++p;
                if (!*p) continue;
                char* end = nullptr;
                const uint64_t off = strtoull(p, &end, 16);
                if (end == p) continue;
                if (off >= img.end() - img.base) { fprintf(stderr, "vpaot: root %#llx is outside the image, ignored\n", (unsigned long long)off); continue; }
                entries.push_back(img.base + off);
                ++added;
            }
            fclose(rf);
            fprintf(stderr, "vpaot: %zu extra roots from %s\n", added, path.c_str());
        }
        Stats stats;
        auto functions = discover(img, entries, stats, opt);
        fprintf(stderr, "vpaot: image %s..%s, %zu executable ranges, %zu code pointers, %zu .eh_frame starts, %zu imports, %zu functions\n",
                std::to_string(img.base).c_str(), std::to_string(img.end()).c_str(), img.executable.size(),
                img.code_pointers.size(), img.eh_frame_starts.size(), img.imports.size(), functions.size());
#ifdef _WIN32
        const std::string c_path = out.empty() ? "NUL" : out;
#else
        const std::string c_path = out.empty() ? "/dev/null" : out;
#endif
        emit_c(img, functions, opt, c_path, stats);
        fprintf(stderr, "vpaot: %" PRIu64 " instructions, %" PRIu64 " unsupported (%.2f%% supported), %" PRIu64
                " indirect calls, %" PRIu64 " indirect jumps, %" PRIu64 " jump tables resolved, %" PRIu64 " landing pads\n",
                stats.instructions, stats.unsupported,
                stats.instructions ? 100.0 * (1.0 - (double)stats.unsupported / (double)stats.instructions) : 100.0,
                stats.indirect_calls, stats.indirect_jumps, stats.jump_tables, stats.landing_pads);
        if (!stats_path.empty() || out.empty()) write_stats(stats, stats_path, img.imports.size());
        return 0;
    } catch (const std::exception& e) {
        fprintf(stderr, "vpaot: %s\n", e.what());
        return 1;
    }
}
