#!/usr/bin/env python3
"""Differential test cases for every instruction form of the PS4's CPU.

  tools/isa_audit (isa_enumerate OUT) lists each form of the AMD Jaguar's instructions with its
  bytes; this writes the ones a test can run alone ("test" in forms.txt) into
  tests/aot/cases/jaguar_<extension>_<n>.s, 48 forms a case, as raw bytes. After a form that leaves
  flags undefined, those flags are cleared (pushfq; and; popfq) so that only defined results are
  compared. run.py then runs each case natively and translated and compares everything.

  make_cases.py FORMS.txt
"""
import collections
import re
import sys
from pathlib import Path

CASES = Path(__file__).resolve().parents[1] / "cases"
PER_CASE = 48
# Run natively only where the CPU has them (run.py "# requires:"): AMD's SSE4a.
REQUIRES = {"SSE4A": "sse4a"}
MXCSR_STORE = re.compile(r"v?stmxcsr\b")

def main():
    forms = collections.defaultdict(list)
    for line in open(sys.argv[1]):
        off, ext, mnem, text, hexbytes, undef, test = line.rstrip("\n").split("\t")
        if test == "test":
            forms[ext].append((text, bytes.fromhex(hexbytes), int(undef, 16)))
    for old in CASES.glob("jaguar_*.s"):
        old.unlink()
    total = 0
    for ext, items in sorted(forms.items()):
        for k in range(0, len(items), PER_CASE):
            chunk = items[k:k + PER_CASE]
            name = f"jaguar_{ext.lower()}_{k // PER_CASE:02d}.s"
            out = [f"# Generated by tests/aot/isa/make_cases.py: {ext} forms {k}..{k + len(chunk) - 1} of the Jaguar's",
                   "# instructions (tools/isa_audit), each as its bytes; undefined flags cleared after it."]
            if ext in REQUIRES:
                out.append(f"# requires: {REQUIRES[ext]}")
            out += [".text", ".globl _start", "_start:"]
            for text, raw, undef in chunk:
                if MXCSR_STORE.match(text):
                    # MXCSR's exception flags are sticky and not modeled (a translated read gives the control
                    # bits only): start each store from FNINIT's state so it checks the store itself.
                    out.append("    pushq $0x1f80; ldmxcsr (%rsp); leaq 8(%rsp), %rsp")
                out.append(f"    .byte {', '.join(f'0x{b:02x}' for b in raw)}  # {text}")
                if undef:
                    out.append(f"    pushfq; andq ${~undef & 0xffffffff:#x} - 0x100000000, (%rsp); popfq" if (~undef & 0x80000000) == 0 else f"    pushfq; andq ${~undef & 0x7fffffff:#x}, (%rsp); popfq")
            out.append("    ret")
            (CASES / name).write_text("\n".join(out) + "\n")
            total += len(chunk)
    print(f"{total} forms in {sum((len(v) + PER_CASE - 1) // PER_CASE for v in forms.values())} cases")

if __name__ == "__main__":
    main()
